-- Verified schema required by the legacy dbo.gup_create_unit procedure.
-- Source: DataBase/Database2/Database2 schema objects and constraints.

CREATE TABLE IF NOT EXISTS GDenyCode
(
    QuestionNo INTEGER NOT NULL,
    CodeNo     INTEGER NOT NULL,
    Comment    TEXT    NOT NULL,
    PRIMARY KEY (QuestionNo, CodeNo)
);

CREATE TABLE IF NOT EXISTS GUnitNickName
(
    UnitUID  INTEGER NOT NULL PRIMARY KEY,
    NickName TEXT NULL,
    RegDate  TEXT NOT NULL,
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS MUK_GUnitNickName_NickName
    ON GUnitNickName (NickName);

CREATE TABLE IF NOT EXISTS GDeletedNickNameHistory
(
    NickName TEXT    NOT NULL,
    UnitUID  INTEGER NOT NULL,
    RegDate  TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS IX_GDeletedNickNameHistory_NickName_RegDate
    ON GDeletedNickNameHistory (NickName, RegDate DESC);

CREATE TABLE IF NOT EXISTS GRecommend
(
    OldUID  INTEGER NOT NULL,
    NewUID  INTEGER NOT NULL,
    RegDate TEXT    NULL
);

CREATE INDEX IF NOT EXISTS IX_GRecommend_NewUID
    ON GRecommend (NewUID);

CREATE TABLE IF NOT EXISTS GDenyOption
(
    UnitUID    INTEGER NOT NULL,
    QuestionNo INTEGER NOT NULL,
    CodeNo     INTEGER NOT NULL,
    PRIMARY KEY (UnitUID, QuestionNo),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (QuestionNo, CodeNo) REFERENCES GDenyCode(QuestionNo, CodeNo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GQuests
(
    UnitUID   INTEGER NOT NULL,
    QuestID   INTEGER NOT NULL,
    SubQuest0 INTEGER NOT NULL,
    SubQuest1 INTEGER NOT NULL,
    SubQuest2 INTEGER NOT NULL,
    SubQuest3 INTEGER NOT NULL,
    SubQuest4 INTEGER NOT NULL,
    RegDate   TEXT NOT NULL,
    PRIMARY KEY (UnitUID, QuestID),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GSkill
(
    UnitUID INTEGER NOT NULL,
    SkillID INTEGER NOT NULL,
    RegDate TEXT    NOT NULL,
    PRIMARY KEY (UnitUID, SkillID),
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GSkillSlot
(
    UnitUID INTEGER NOT NULL PRIMARY KEY,
    Slot01  INTEGER NOT NULL,
    Slot02  INTEGER NOT NULL,
    Slot03  INTEGER NOT NULL,
    FOREIGN KEY (UnitUID) REFERENCES GUnit(UnitUID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GSpirit
(
    unitUID INTEGER NOT NULL PRIMARY KEY,
    Spirit  INTEGER NOT NULL,
    RegDate TEXT    NOT NULL,
    Flag    INTEGER NOT NULL DEFAULT 0 CHECK (Flag IN (0, 1)),
    FOREIGN KEY (unitUID) REFERENCES GUnit(UnitUID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GResurrectionStoneCnt
(
    StartCnt    INTEGER NULL,
    SupplyCnt   INTEGER NULL,
    StartSpirit INTEGER NULL
);
