<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>KncWX2Server.Core.RegressionTests</RootNamespace>
    <AssemblyName>KncWX2Server.Core.RegressionTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../KncWX2Server.Core/KncWX2Server.Core.csproj" />
    <ProjectReference Include="../KncWX2Server.LoginServer/KncWX2Server.LoginServer.csproj" />
  </ItemGroup>
</Project>
