//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by X2WorldTool.rc
//
#define IDI_MAIN_ICON                   101
#define IDD_DIALOG1                     113
#define IDD_DIALOG2                     114
#define IDD_DIALOG3                     116
#define IDI_ICON1                       116
#define IDD_DIALOG4                     120
#define IDD_PARTICLE_EDITOR             121
#define IDR_ACCELERATOR1                122
#define IDD_MESH_EDITOR                 123
#define IDI_ICON2                       127
#define IDD_PARTICLE_EDITOR2            128
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_EDIT6                       1005
#define IDC_EDIT7                       1006
#define IDC_EDIT8                       1007
#define LM_IDC_EDIT9                    1008
#define LM_IDC_EDIT10                   1009
#define IDC_COMBO1                      1010
#define T_EDIT_LINE_SPEED               1010
#define IDC_LIST2                       1011
#define LM_IDC_COMBO3                   1011
#define IDC_COMBO2                      1012
#define LM_IDC_EDIT11                   1012
#define IDC_STATIC_TEXNAME              1013
#define LM_IDC_EDIT12                   1013
#define T_LIST_DATA                     1014
#define LM_IDC_EDIT13                   1015
#define IDC_SLIDER2                     1016
#define LM_IDC_EDIT14                   1016
#define IDC_SLIDER3                     1017
#define LM_IDC_EDIT15                   1017
#define IDC_SLIDER4                     1018
#define LM_IDC_EDIT16                   1018
#define IDC_STATIC_RED                  1019
#define LM_IDC_EDIT17                   1019
#define IDC_STATIC_GREEN                1020
#define LM_IDC_EDIT18                   1020
#define IDC_STATIC_BLUE                 1021
#define LM_IDC_EDIT19                   1021
#define IDC_BUTTON1                     1022
#define T_LIST_MESH                     1022
#define IDC_BUTTON2                     1023
#define T_LIST_LINE                     1023
#define LM_IDOK                         1024
#define IDC_STATIC_BLUE2                1024
#define LM_IDCANCEL                     1025
#define IDC_SLIDER5                     1025
#define LM_IDC_LIST1                    1026
#define LM_IDC_CHECK1                   1027
#define LM_IDC_CHECK2                   1028
#define LM_IDC_CHECK3                   1029
#define LM_IDC_CHECK4                   1030
#define LM_IDC_CHECK5                   1031
#define LM_IDC_CHECK6                   1032
#define LM_IDC_CHECK7                   1033
#define LM_IDC_COMBO1                   1034
#define LM_IDC_EDIT1                    1035
#define LM_IDC_EDIT2                    1036
#define LM_IDC_EDIT3                    1037
#define LM_IDC_EDIT4                    1038
#define LM_IDC_EDIT6                    1039
#define LM_IDC_EDIT7                    1040
#define LM_IDC_EDIT8                    1041
#define LM_IDC_EDIT20                   1042
#define LM_IDC_EDIT21                   1043
#define LM_IDC_EDIT22                   1044
#define LM_IDC_BUTTON_SAVE              1045
#define LM_IDC_BUTTON2                  1046
#define LM_IDC_EDIT_START               1047
#define LM_IDC_EDIT_END                 1048
#define LM_IDC_CHECK_FORCE_COLOR        1049
#define T_COMBO_LINE_ACTION             1050
#define LM_IDC_LIST_CAMERA              1051
#define PA_COMBO_EventType              1051
#define LM_IDC_EDIT_CAMERA1             1052
#define PA_COMBO_Particle               1052
#define LM_IDC_EDIT_CAMERA2             1053
#define PA_COMBO_Billboard              1053
#define LM_IDC_EDIT_CAMERA3             1054
#define PA_COMBO_MeshRender             1054
#define LM_IDC_EDIT_CAMERA4             1055
#define PA_COMBO_SourceBlend            1055
#define T_EDIT_LINE_JUMPSPEEDX          1056
#define PA_COMBO_DestBlend              1056
#define LM_IDC_COMBO_CAMERA             1057
#define PA_COMBO_CullMode               1057
#define LM_IDC_CHECK_CAMERA             1058
#define PA_COMBO_LifeType               1058
#define LM_IDC_BUTTON_GETCAMERA         1059
#define PA_COMBO_DieType                1059
#define LM_IDC_BUTTON_ADDCAMERA         1060
#define PA_COMBO_CartoonTexType         1060
#define LM_IDC_EDIT_CAMERAINDEX         1061
#define PA_COMBO_TraceCurveType         1061
#define LM_IDC_BUTTON_ADDCAMERA2        1062
#define PA_COMBO_SlashTraceType         1062
#define T_EDIT1_LINE_JUMPSPEEDY         1063
#define PA_COMBO_PlayType               1063
#define LM_IDC_LIST_RED                 1064
#define PA_COMBO_EVENT_RENDER_TYPE      1064
#define LM_IDC_LIST_BLUE                1065
#define LM_IDC_LIST_OTHER               1066
#define LM_IDC_RADIO_RED                1067
#define LM_IDC_RADIO_BLUE               1068
#define LM_IDC_RADIO_OTHER              1069
#define LM_IDC_COMBO_DIR                1070
#define T_COMBO_ETC_ACTION              1071
#define T_EDIT_DELAYTIME                1072
#define LM_IDC_BUTTON_DELETENPC         1073
#define LM_IDC_CHECK_HIDE_USER          1074
#define LM_IDC_CHECK_HIDENPC            1075
#define LM_IDC_BUTTON_RESETKEY          1076
#define T_EDIT_ETC_NAME                 1077
#define LM_IDC_COMBO_TEAMTYPE           1078
#define LM_IDC_BUTTON_CHANGE            1079
#define LM_IDC_CHECK_HIDEWORLD          1080
#define T_LIST_ETC                      1081
#define LM_IDC_EDIT_TRIGGERID           1082
#define T_EDIT_ETC_CAMERA               1083
#define T_COMBO_MESH_PLAYTYPE           1084
#define T_CHECK_LINE_ENABLE             1085
#define T_COMBO_MESH_ANIMNAME           1086
#define T_CHECK_LOOP                    1087
#define T_LIST_SEG                      1088
#define T_COMBO_MESH_ID                 1089
#define T_COMBO_MESH_ACTION             1090
#define T_EDIT_MESH_DELAYTIME           1091
#define T_EDIT_ETC_CAMERADURATION       1092
#define LM_IDC_EDIT_LANDHEIGHT          1093
#define T_EDIT_ANIMSPEED                1094
#define T_EDIT_LINE_DELAYTIME           1095
#define T_EDIT_LINEID                   1096
#define PA_EDIT_TimeValue2              1096
#define T_EDIT_LINE_CAMERAID            1097
#define T_TRIGGER_ADD                   1098
#define T_TRIGGER_ADD_ETC               1099
#define T_TRIGGER_ADD_MESH              1100
#define T_TRIGGER_ADD_LINE              1101
#define T_UPDATE_LINE                   1102
#define T_UPDATE_ETC                    1103
#define T_UPDATE_MESH                   1104
#define T_TRIGGER_ADD_DATA              1105
#define T_UPDATE_TRIGGER                1106
#define T_TRIGGER_ADD_MESH2             1107
#define IDC_WONPOK                      1107
#define LM_IDC_COMBO2                   1108
#define T_BUTTON_INITWORLD              1109
#define PA_EDIT_STRING                  1109
#define LM_IDC_EDIT5                    1110
#define PA_EDIT_Layer                   1110
#define PA_EDIT_Numparticles            1111
#define IDC_LAYER_CHECK1                1112
#define PA_EDIT_Mesh                    1112
#define PA_EDIT_Priority                1112
#define PA_EDIT_LifeTime_Min            1113
#define IDC_FRU_EDIT1                   1114
#define PA_EDIT_LifeTime_Max            1114
#define IDC_FRU_EDIT2                   1115
#define PA_EDIT_EmitRate_Min            1115
#define IDC_FRU_EDIT3                   1116
#define PA_EDIT_EmitRate_Max            1116
#define FRU_IDOK                        1117
#define PA_EDIT_TriggerTime_Min         1117
#define PA_EDIT_TriggerTime_Max         1118
#define IDC_FRU_EDIT4                   1118
#define PA_EDIT_AniName2                1118
#define PA_EDIT_DrawCount_Min           1119
#define PA_EDIT_AniName3                1119
#define PA_EDIT_FINAL_SEQ_NAME          1119
#define PA_EDIT_DrawCount_Max           1120
#define PA_EDIT_EmitRadius_Minx         1121
#define IDC_FRU_EDIT5                   1121
#define PA_EDIT_EmitRadius_MaxX         1122
#define IDC_FRU_EDIT6                   1122
#define IDC_FRU_EDIT7                   1123
#define PA_EDIT_EmitRadius_MinY         1123
#define PA_EDIT_EmitRadius_MaxY         1124
#define PA_EDIT_EmitRadius_MinZ         1125
#define PA_EDIT_EmitRadius_MaxZ         1126
#define PA_EDIT_Gravity_MinX            1127
#define PA_EDIT_Gravity_MaxX            1128
#define PA_EDIT_Gravity_MinY            1129
#define PA_EDIT_Gravity_MaxY            1130
#define PA_EDIT_Gravity_MinZ            1131
#define PA_EDIT_Gravity_MaxZ            1132
#define PA_COMBO_VECTOR3_MinX           1133
#define PA_COMBO_VECTOR3_MaxX           1134
#define PA_COMBO_VECTOR3_MinY           1135
#define PA_COMBO_VECTOR3_MaxY           1136
#define PA_COMBO_VECTOR3_MinZ           1137
#define PA_COMBO_VECTOR3_MaxZ           1138
#define PA_COMBO_VECTOR2_MinX           1139
#define PA_COMBO_VECTOR2_MaxX           1140
#define PA_COMBO_VECTOR2_MinY           1141
#define PA_COMBO_VECTOR2_MaxY           1142
#define PA_EDIT_PARTICLE_NAME           1143
#define PA_EDIT_LINE_RotateRel_MinX     1144
#define PA_EDIT_RotateRel_MinX          1144
#define PA_COMBO_FLOAT_Min              1145
#define PA_COMBO_FLOAT_Max              1146
#define PA_IDC_Enable                   1147
#define PA_EDIT_PARTICLE_FILE_NAME      1147
#define PA_EDIT_BlackHolePos_MinX       1147
#define PA_IDC_ZEnable                  1148
#define PA_IDC_ApplyUnitScale           1149
#define PA_IDC_Trace                    1150
#define PA_LIST_EventList               1151
#define PA_IDC_EvnetList_ADD            1152
#define PA_BUTTON_Trace_Seq_ADD         1152
#define PA_IDC_EvnetList_DEL            1153
#define PA_BUTTON_Trace_Seq_DEL         1153
#define PA_COMBO_TimeType               1154
#define PA_LIST_EventList2              1154
#define PA_LIST_FINAL_SEQ_NAME          1154
#define PA_EDIT_TimeValue1              1155
#define PA_IDC_EvnetList_ADD2           1155
#define PA_BUTTON_Final_Seq_ADD         1155
#define PA_IDC_UseLand                  1156
#define PA_IDC_EvnetList_DEL2           1156
#define PA_BUTTON_Final_Seq_DEL         1156
#define PA_EDIT_RotateRel_MaxX          1157
#define PA_LIST_EventList_Anim          1157
#define PA_EDIT_RotateRel_MinY          1158
#define PA_IDC_EvnetList_Anim_ADD       1158
#define PA_EDIT_RotateRel_MaxY          1159
#define PA_IDC_EvnetList_Anim_DEL       1159
#define PA_EDIT_RotateRel_MinZ          1160
#define PA_LIST_EventList_Die           1160
#define PA_EDIT_RotateRel_MaxZ          1161
#define PA_IDC_EvnetList_Die_ADD        1161
#define PA_EDIT_LightPos_MinX           1162
#define PA_EDIT_LightPos_MaxX           1163
#define PA_EDIT_LightPos_MinY           1164
#define PA_EDIT_LightPos_MaxY           1165
#define PA_EDIT_LightPos_MinZ           1166
#define PA_EDIT_LightPos_MaxZ           1167
#define PA_COMBO_COLOR_MinR             1168
#define PA_COMBO_COLOR_MaxR             1169
#define PA_EDIT_TriggerCount_Min        1170
#define PA_EDIT_TriggerCount_Max        1171
#define PA_COMBO_COLOR_MinG             1172
#define PA_COMBO_COLOR_MaxG             1173
#define PA_COMBO_COLOR_MinB             1174
#define PA_COMBO_COLOR_MaxB             1175
#define PA_COMBO_COLOR_MinA             1176
#define PA_COMBO_COLOR_MaxA             1177
#define PA_EDIT_LandPosition_Min        1178
#define PA_EDIT_LandPosition_Max        1179
#define LM_IDC_CHECK_ONLINE             1180
#define PA_BUTTON_EVENT_STRING          1180
#define PA_COMBO_MeshType               1181
#define PA_EDIT_ChangeXet               1181
#define PA_EDIT_MESH_NAME               1182
#define PA_BUTTON_EVENT_STRING2         1182
#define PA_BUTTON_MESH_NAME_STRING      1182
#define PA_EDIT_MeshName                1183
#define PA_IDC_EvnetList_UP             1183
#define PA_EDIT_SlashTraceTextureName   1184
#define PA_IDC_EvnetList_DOWN           1184
#define PA_EDIT_PlayCount_Min           1185
#define PA_IDC_ZWrtieEnable2            1185
#define PA_IDC_ZWriteEnable2            1185
#define PA_EDIT_PlayCount_Max           1186
#define PA_EDIT_DiePlayCount_Min        1187
#define PA_EDIT_DiePlayCount_Max        1188
#define PA_EDIT_BlackHolePos_MaxX       1189
#define PA_EDIT_BlackHolePos_MinY       1190
#define PA_EDIT_BlackHolePos_MaxY       1191
#define PA_EDIT_BlackHolePos_MinZ       1192
#define PA_EDIT_BlackHolePos_MaxZ       1193
#define PA_EDIT_DieLifeTime_Min         1194
#define PA_EDIT_DieLifeTime_Max         1195
#define PA_IDC_ZWriteEnable             1196
#define PA_IDC_SetLandHeightOnStart     1197
#define PA_IDC_CrashLand                1198
#define PA_EDIT_NotCheckLandTime        1199
#define PA_EDIT_ChangeTexXetName        1200
#define PA_EDIT_MultiTexXetName         1201
#define PA_EDIT_AniXetName              1202
#define PA_EDIT_OutLineWide_Min         1203
#define PA_EDIT_OutLineWide_Max         1204
#define PA_EDIT_LightFlowWide_Min       1205
#define PA_EDIT_LightFlowWide_Max       1206
#define PA_EDIT_elasticCoeff_Min        1207
#define PA_EDIT_elasticCoeff_Max        1208
#define PA_EDIT_elasticCoeffX_Min       1209
#define PA_EDIT_elasticCoeffX_Max       1210
#define PA_EDIT_MESH_TEMPLET_NAME       1211
#define PA_IDC_EvnetList_Die_DEL        1212
#define PA_LIST_EventList_Global        1213
#define PA_IDC_EvnetList_Global_ADD     1214
#define PA_IDC_EvnetList_Global_DEL     1215
#define PA_IDC_bUseDieEvent             1216
#define PA_IDC_bForceLayer              1217
#define PA_IDC_EVENT_USE_SLASH_TRACE    1218
#define PA_IDC_USE_SLASH_TRACE          1219
#define PA_CHECK_UseDXMatrix            1221
#define PA_CHECK_ReverseY               1222
#define PA_IDC_EvnetList_Die_UP         1222
#define PA_CHECK_CullingCheck           1223
#define PA_IDC_EvnetList_DOWN2          1223
#define PA_IDC_EvnetList_Die_DOWN       1223
#define PA_CHECK_TriggerWait            1224
#define PA_IDC_EvnetList_Anim_UP        1224
#define PA_CHECK_Delete                 1225
#define PA_IDC_EvnetList_Anim_DOWN      1225
#define PA_CHECK_InChain                1226
#define PA_IDC_EvnetList_Global_UP      1226
#define PA_CHECK_DynamicChain           1227
#define PA_IDC_EvnetList_Global_DOWN    1227
#define PA_CHECK_ResolutionConvert      1228
#define PA_CHECK_UseLookPoint           1229
#define PA_EDIT_LatencyTime             1230
#define PA_EDIT_SphericalEmitRadius_Min 1231
#define PA_EDIT_SphericalEmitRadius_Max 1232
#define PA_EDIT_SphericalEmitRotation_MinX 1233
#define PA_EDIT_SphericalEmitRotation_MinY 1234
#define PA_EDIT_SphericalEmitRotation_MinZ 1235
#define PA_EDIT_SphericalEmitRotation_MaxZ 1236
#define PA_EDIT_SphericalEmitRotation_MaxY 1237
#define PA_EDIT_SphericalEmitRotation_MaxX 1238
#define PA_EDIT_NumNewPartsExcess       1239
#define PA_EDIT_ScrewValue              1240
#define PA_EDIT_ScrewRotateSpeed        1241
#define PA_EDIT_AniName                 1242
#define PA_LIST_TRACE_SEQ_NAME          1243
#define PA_EDIT_TRACE_SEQ_NAME          1244
#define PA_EDIT_SphericalEmitAzimuth_Min 1245
#define PA_EDIT_SphericalEmitAzimuth_Max 1246
#define PA_EDIT_SphericalEmitPolar_Min  1247
#define PA_EDIT_SphericalEmitPolar_Max  1248

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1245
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
