CREATE PROCEDURE [dbo].[ADBILLGAME_PLUS_IP_CHECK]
	@IPCBANG_IP [varchar](15),
	@ORETVAL [int] OUTPUT,
	@OCONTENTS_NO [int] OUTPUT
AS
set nocount on

DECLARE @BCONTENTS_NO INT
	SELECT @BCONTENTS_NO = 0

	IF EXISTS (SELECT * FROM dbo.GC_PCBANG_IP (NOLOCK) WHERE IP = RTRIM(@IPCBANG_IP) AND FLAG = '0' )
	BEGIN
		SELECT @OCONTENTS_NO = @BCONTENTS_NO
		SELECT @ORETVAL = 1
		RETURN @ORETVAL
	END
	ELSE
	BEGIN
		SELECT @OCONTENTS_NO = 0
		SELECT @ORETVAL = 0
		RETURN @ORETVAL
	END


