#pragma once

#define	STRINGMAIN00 L"Logge dich über"
#define	STRINGMAIN01 L"die Homepage ein!"
#define	STRINGMAIN02 L"Elsword"
#define	STRINGMAIN03 L"Patch-Programm wird gestartet."
#define	STRINGMAIN04 L"Elsword wird"
#define	STRINGMAIN05 L"bereits ausgeführt."
#define	STRINGMAIN06 L"DirectX 9.0c wird heruntergeladen."
#define	STRINGMAIN07 	
#define	STRINGMAIN08 L"Download des DirectX 9.0c File fehlgeschlagen!"
#define	STRINGMAIN09 L"Klicke auf \"Bestätigen\"."
#define	STRINGMAIN10 L"DirectX 9.0c wird installiert."
#define	STRINGMAIN11 L"Klicke auf \"Bestätigen\"."
#define	STRINGMAIN12 L"Erstellen des Patchprogramm-Fensters fehlgeschlagen."
#define	STRINGMAIN13 L"Bitte erneut ausführen."
#define	STRINGMAIN14 L"Sollen der Patch-Download und das Spiel"
#define	STRINGMAIN15 L"abgebrochen werden?"
#define	STRINGMAIN16 L"Ausführen des Spiels fehlgeschlagen."
#define	STRINGMAIN17 L"Bitte versuche es erneut."
#define	STRINGMAIN18 L"Sollen der Patch-Download und das Spiel"
#define	STRINGMAIN19 L"abgebrochen werden?"
#define	STRINGMAIN20 L"Das Programm wird beendet."
#define	STRINGMAIN21 L"Bitte versuche es in 30 Sekunden erneut."
#define	STRINGMAIN22 L"Ausführen des Spiels fehlgeschlagen."
#define	STRINGMAIN23 L"Bitte versuche es erneut."

#define	STRINGPATCHER00 L"Update des Version Files fehlgeschlagen."
#define	STRINGPATCHER01 L"Bitte versuche es erneut."
#define	STRINGPATCHER02 L"Patch-Vorgang wird ausgeführt."
#define	STRINGPATCHER03 L"Patch Process File wird heruntergeladen."
#define	STRINGPATCHER04 L"Patchserver-Verbindung fehlgeschlagen."
#define	STRINGPATCHER05 L"Bitte versuche es erneut."
#define	STRINGPATCHER06 L"Download des Process File fehlgeschlagen."
#define	STRINGPATCHER07 L"Bitte versuche es erneut."
#define	STRINGPATCHER08 L"Process File lesen fehlgeschlagen."
#define	STRINGPATCHER09 L"Bitte versuche es erneut."
#define	STRINGPATCHER10 L"Patch-Vorgang wird ausgeführt."
#define	STRINGPATCHER11 L"Version File wird heruntergeladen."
#define	STRINGPATCHER12 L"Download der Versions Datei fehlgeschlagen."
#define	STRINGPATCHER13 L"Bitte versuche es erneut."
#define	STRINGPATCHER14 L"Lesen der Versions Datei fehlgeschlagen."
#define	STRINGPATCHER15 L"Bitte versuche es erneut."
#define	STRINGPATCHER16 L"Die neue Version wird mit"
#define	STRINGPATCHER17 L"der installierten Version verglichen."
#define	STRINGPATCHER18 L"Vergleich der Versionen fehlgeschlagen."
#define	STRINGPATCHER19 L"Bitte versuche es erneut."
#define	STRINGPATCHER20 L"Download der Patch-Datei fehlgeschlagen."
#define	STRINGPATCHER21 L"Bitte versuche es erneut."
#define	STRINGPATCHER22 L"Installation beendet."
#define	STRINGPATCHER23 L"Klicke auf \"Ausführen\", um das Spiel zu starten."
					    
#define	STRINGPATCHER35 L""
