#pragma once

#define STRINGMAIN00 L"Log in through"
#define STRINGMAIN01 L"the homepage!"
#define STRINGMAIN02 L"Elsword"
#define STRINGMAIN03 L"Patch program is being started."
#define STRINGMAIN04 L"Elsword is"
#define STRINGMAIN05 L"already executed."
#define STRINGMAIN06 L"DirectX 9.0c is being downloaded."
#define STRINGMAIN07 
#define STRINGMAIN08 L"Download of DirectX 9.0c file failed!"
#define STRINGMAIN09 L"Click \"Confirm\"."
#define STRINGMAIN10 L"DirectX 9.0c is being installed."
#define STRINGMAIN11 L"Click \"Confirm\"."
#define STRINGMAIN12 L"Launching of patch program window failed."
#define STRINGMAIN13 L"Please run again."
#define STRINGMAIN14 L"Cancel patch download"
#define STRINGMAIN15 L"and the game?"
#define STRINGMAIN16 L"Game execution failed."
#define STRINGMAIN17 L"Please try again."
#define STRINGMAIN18 L"Cancel patch download"
#define STRINGMAIN19 L"and the game?"
#define STRINGMAIN20 L"The program will close."
#define STRINGMAIN21 L"Please try again in 30 seconds."
#define STRINGMAIN22 L"Game execution failed."
#define STRINGMAIN23 L"Please try again."

#define STRINGPATCHER00 L"Updating of version file failed."
#define STRINGPATCHER01 L"Please try again."
#define STRINGPATCHER02 L"Patch procedure is being executed."
#define STRINGPATCHER03 L"Patch process file is being downloaded."
#define STRINGPATCHER04 L"Patch server connection failed."
#define STRINGPATCHER05 L"Please try again."
#define STRINGPATCHER06 L"Process file download failed."
#define STRINGPATCHER07 L"Please try again."
#define STRINGPATCHER08 L"Failed to read process file."
#define STRINGPATCHER09 L"Please try again."
#define STRINGPATCHER10 L"Patch procedure is being executed."
#define STRINGPATCHER11 L"Version file is being downloaded."
#define STRINGPATCHER12 L"Version file download failed."
#define STRINGPATCHER13 L"Please try again."
#define STRINGPATCHER14 L"Failed to read version file."
#define STRINGPATCHER15 L"Please try again."
#define STRINGPATCHER16 L"The new version must be compared with"
#define STRINGPATCHER17 L"the installed version."
#define STRINGPATCHER18 L"Version comparison failed."
#define STRINGPATCHER19 L"Please try again."
#define STRINGPATCHER20 L"Patch file download failed."
#define STRINGPATCHER21 L"Please try again."
#define STRINGPATCHER22 L"Installation ended."
#define STRINGPATCHER23 L"Click on \"Execute\" to start the game."

#define	STRINGPATCHER35	L""