#pragma once

#define STRINGMAIN00 L"ホームページを通して",
#define STRINGMAIN01 L"接続してください!",
#define STRINGMAIN02 L"エルソード",
#define STRINGMAIN03 L"パッチプログラムをスタートします",
#define STRINGMAIN04 L"すでにエルソードが",
#define STRINGMAIN05 L"実行中です",
#define STRINGMAIN06 L"DirectX 9.0cをダウンしています",
#define STRINGMAIN07 L"",
#define STRINGMAIN08 L"DirectX 9.0cファイル受け取り失敗!",
#define STRINGMAIN09 L"\'確認\'ボタンを押してください",
#define STRINGMAIN10 L"DirectX 9.0cを設置します",
#define STRINGMAIN11 L"\'確認\'ボタンを押してください",
#define STRINGMAIN12 L"パッチプログラムウィンドー生成失敗",
#define STRINGMAIN13 L"もう一度実行してください",
#define STRINGMAIN14 L"パッチダウンロードとエルソードの",
#define STRINGMAIN15 L"実行をキャンセルしますか？",
#define STRINGMAIN16 L"ゲーム実行に失敗しました",
#define STRINGMAIN17 L"もう一度実行してください",
#define STRINGMAIN18 L"パッチダウンロードとエルソードの",
#define STRINGMAIN19 L"実行をキャンセルしますか？",
#define STRINGMAIN20 L"プログラムを終了します",
#define STRINGMAIN21 L"再実行は30秒後にしてください",
#define STRINGMAIN22 L"ゲーム実行に失敗しました",
#define STRINGMAIN23 L"もう一度実行してください",

#define STRINGPATCHER00 L"バージョンファイルアップデート失敗",
#define STRINGPATCHER01 L"もう一度実行してください",
#define STRINGPATCHER02 L"パッチ作業遂行中です",
#define STRINGPATCHER03 L"パッチ経路ファイルダウンロード中です",
#define STRINGPATCHER04 L"パッチサーバー接続失敗",
#define STRINGPATCHER05 L"もう一度実行してください",
#define STRINGPATCHER06 L"経路ファイル受け取り失敗",
#define STRINGPATCHER07 L"もう一度実行してください",
#define STRINGPATCHER08 L"経路ファイル読み取り失敗",
#define STRINGPATCHER09 L"もう一度実行してください",
#define STRINGPATCHER10 L"パッチ作業遂行中です",
#define STRINGPATCHER11 L"バージョンファイルダウンロード中",
#define STRINGPATCHER12 L"バージョンファイル受け取り失敗",
#define STRINGPATCHER13 L"もう一度実行してください",
#define STRINGPATCHER14 L"バージョンファイル読み取り失敗",
#define STRINGPATCHER15 L"もう一度実行してください",
#define STRINGPATCHER16 L"新しいバージョンと設置されたバージョンを",
#define STRINGPATCHER17 L"比較中です",
#define STRINGPATCHER18 L"バージョン比較作業失敗",
#define STRINGPATCHER19 L"もう一度実行してください",
#define STRINGPATCHER20 L"パッチファイル受け取り失敗",
#define STRINGPATCHER21 L"もう一度実行してください",
#define STRINGPATCHER22 L"設置が完了されました",
#define STRINGPATCHER23 L"\'実行\'ボタンを押してゲームをスタートしてください"
#define	STRINGPATCHER35	L"パッチャ?の更新が完了しました。"