#pragma once
#define STRINGMAIN00 L"¡Regístrate en la"
#define STRINGMAIN01 L"página principal!"
#define STRINGMAIN02 L"Elsword"
#define STRINGMAIN03 L"El parche se está iniciando."
#define STRINGMAIN04 L"Elsword se"
#define STRINGMAIN05 L"está ejecutando."
#define STRINGMAIN06 L"DirectX 9.0c se está descargando."
#define STRINGMAIN07 L"" 
#define STRINGMAIN08 L"¡Error al descargar el archivo DirectX 9.0c!"
#define STRINGMAIN09 L"Haz clic en \"Confirmar\"."
#define STRINGMAIN10 L"DirectX 9.0c se está instalando."
#define STRINGMAIN11 L"Haz clic en \"Confirmar\"."
#define STRINGMAIN12 L"Error al abrir la ventana del parche."
#define STRINGMAIN13 L"Ejecuta de nuevo el programa."
#define STRINGMAIN14 L"¿Quieres interrumpir"
#define STRINGMAIN15 L"la descarga del parche y el juego?"
#define STRINGMAIN16 L"Error al ejecutar el juego."
#define STRINGMAIN17 L"Inténtalo de nuevo."
#define STRINGMAIN18 L"¿Quieres interrumpir"
#define STRINGMAIN19 L"la descarga del parche y el juego?"
#define STRINGMAIN20 L"Se está cerrando el programa."
#define STRINGMAIN21 L"Inténtalo de nuevo en 30 segundos."
#define STRINGMAIN22 L"Error al ejecutar el juego."
#define STRINGMAIN23 L"Inténtalo de nuevo." 
#define STRINGPATCHER00 L"Error al actualizar el archivo de versión."
#define STRINGPATCHER01 L"Inténtalo de nuevo."
#define STRINGPATCHER02 L"El parcheo se está ejecutando."
#define STRINGPATCHER03 L"El archivo de parcheo se está descargando."
#define STRINGPATCHER04 L"Error al conectar con el servidor del parche."
#define STRINGPATCHER05 L"Inténtalo de nuevo."
#define STRINGPATCHER06 L"Error al descargar el archivo de proceso."
#define STRINGPATCHER07 L"Inténtalo de nuevo."
#define STRINGPATCHER08 L"Error al leer el archivo de proceso."
#define STRINGPATCHER09 L"Inténtalo de nuevo."
#define STRINGPATCHER10 L"El parcheo se está ejecutando."
#define STRINGPATCHER11 L"El archivo de versión se está descargando."
#define STRINGPATCHER12 L"Error al descargar el archivo de versión."
#define STRINGPATCHER13 L"Inténtalo de nuevo."
#define STRINGPATCHER14 L"Error al leer el archivo de versión."
#define STRINGPATCHER15 L"Inténtalo de nuevo."
#define STRINGPATCHER16 L"Se está comparando"
#define STRINGPATCHER17 L"la versión nueva con la ya instalada."
#define STRINGPATCHER18 L"Error al comparar ambas versiones."
#define STRINGPATCHER19 L"Inténtalo de nuevo."
#define STRINGPATCHER20 L"Error al descargar el archivo de parche."
#define STRINGPATCHER21 L"Inténtalo de nuevo."
#define STRINGPATCHER22 L"Instalación completada."
#define STRINGPATCHER23 L"Haz clic en \"Ejecutar\" para iniciar el juego."

#define	STRINGPATCHER35	L""
