#pragma once
#define	STRINGMAIN00 L"Effettua il login a partire"
#define	STRINGMAIN01 L"dalla homepage!"
#define	STRINGMAIN02 L"Elsword"
#define	STRINGMAIN03 L"La patch è in fase di avvio."
#define	STRINGMAIN04 L"Elsword è"
#define	STRINGMAIN05 L"già in esecuzione."
#define	STRINGMAIN06 L"DirectX 9.0c è in fase di download."
#define	STRINGMAIN07 L""
#define	STRINGMAIN08 L"Il download di DirectX 9.0c non è riuscito!"
#define	STRINGMAIN09 L"Clicca su \"Conferma\"."
#define	STRINGMAIN10 L"DirectX 9.0c è in fase di installazione."
#define	STRINGMAIN11 L"Clicca su \"Conferma\"."
#define	STRINGMAIN12 L"L'apertura della finestra della patch non è riuscita."
#define	STRINGMAIN13 L"Esegui nuovamente il programma."
#define	STRINGMAIN14 L"Vuoi che il gioco e il download della patch"
#define	STRINGMAIN15 L"vengano interrotti?"
#define	STRINGMAIN16 L"L'esecuzione del gioco non è riuscita."
#define	STRINGMAIN17 L"Ritenta nuovamente."
#define	STRINGMAIN18 L"Vuoi che il gioco e il download della patch"
#define	STRINGMAIN19 L"vengano interrotti?"
#define	STRINGMAIN20 L"Il programma sta per essere chiuso."
#define	STRINGMAIN21 L"Ritenta nuovamente fra 30 secondi."
#define	STRINGMAIN22 L"L'avvio del gioco non è riuscito."
#define	STRINGMAIN23 L"Ritenta nuovamente."
#define	STRINGPATCHER00 L"Aggiornamento del file di versione non riuscito."
#define	STRINGPATCHER01 L"Ritenta nuovamente."
#define	STRINGPATCHER02 L"La procedura di patch è in esecuzione."
#define	STRINGPATCHER03 L"Il file del processo di patch è in fase di download."
#define	STRINGPATCHER04 L"La connessione con il server della patch non è riuscita."
#define	STRINGPATCHER05 L"Ritenta nuovamente."
#define	STRINGPATCHER06 L"Il download del file del processo non è riuscito."
#define	STRINGPATCHER07 L"Ritenta nuovamente."
#define	STRINGPATCHER08 L"La lettura del file del processo non è riuscita."
#define	STRINGPATCHER09 L"Ritenta nuovamente."
#define	STRINGPATCHER10 L"La procedura di patch è in esecuzione."
#define	STRINGPATCHER11 L"Il file di versione è in fase di download."
#define	STRINGPATCHER12 L"Il download dei dati versione non è riuscito."
#define	STRINGPATCHER13 L"Ritenta nuovamente."
#define	STRINGPATCHER14 L"La lettura del file versione non è riuscita."
#define	STRINGPATCHER15 L"Ritenta nuovamente."
#define	STRINGPATCHER16 L"La nuova versione viene"
#define	STRINGPATCHER17 L"confrontata con quella già installata."
#define	STRINGPATCHER18 L"Il confronto tra le due versioni non è riuscito."
#define	STRINGPATCHER19 L"Ritenta nuovamente."
#define	STRINGPATCHER20 L"Il download dei dati della patch non è riuscito."
#define	STRINGPATCHER21 L"Ritenta nuovamente."
#define	STRINGPATCHER22 L"L'installazione è completa."
#define	STRINGPATCHER23 L"Clicca su \"Esegui\" per iniziare a giocare."

#define	STRINGPATCHER35	L""
