#pragma once
#define STRINGMAIN00 L"Zaloguj się przez"
#define STRINGMAIN01 L"stronę główną!"
#define STRINGMAIN02 L"Elsword"
#define STRINGMAIN03 L"Program patch zostanie uruchomiony."
#define STRINGMAIN04 L"Elsword jest"
#define STRINGMAIN05 L"już wygrywany."
#define STRINGMAIN06 L"DirectX 9.0c zostanie pobrany."
#define STRINGMAIN07 L""
#define STRINGMAIN08 L"Pobranie pliku DirectX 9.0c nie powiodło się."
#define STRINGMAIN09 L"Kliknij na \"Potwierdzam\"."
#define STRINGMAIN10 L"DirectX 9.0c zostanie zainstalowany."
#define STRINGMAIN11 L"Kliknij na \"Potwierdzam\"."
#define STRINGMAIN12 L"Tworzenie okna programu patch nie powiodło się."
#define STRINGMAIN13 L"Spróbuj ponownie."
#define STRINGMAIN14 L"Czy przerwać pobieranie programu patch"
#define STRINGMAIN15 L"i zakończyć grę?"
#define STRINGMAIN16 L"Wygrywanie gry nie powiodło się."
#define STRINGMAIN17 L"Spróbuj później ponownie."
#define STRINGMAIN18 L"Czy przerwać pobieranie programu patch"
#define STRINGMAIN19 L"i zakończyć grę?"
#define STRINGMAIN20 L"Program zostanie zakończony."
#define STRINGMAIN21 L"Spróbuj ponownie za 30 sekund."
#define STRINGMAIN22 L"Wygrywanie gry nie powiodło się."
#define STRINGMAIN23 L"Spróbuj później ponownie."
#define STRINGPATCHER00 L"Aktualizacja pliku wersji nie powiodła się."
#define STRINGPATCHER01 L"Spróbuj później ponownie."
#define STRINGPATCHER02 L"Proces patch jest wgrywany."
#define STRINGPATCHER03 L"Lista procesów do pliku jest pobierana."
#define STRINGPATCHER04 L"Połączenie programu patch z serwerem nie powiodło się."
#define STRINGPATCHER05 L"Spróbuj później ponownie."
#define STRINGPATCHER06 L"Pobranie listy procesów do pliku nie powiodło się."
#define STRINGPATCHER07 L"Spróbuj ponownie."
#define STRINGPATCHER08 L"Czytanie listy procesów do pliku nie powiodło się."
#define STRINGPATCHER09 L"Spróbuj ponownie."
#define STRINGPATCHER10 L"Patch jest wgrywany."
#define STRINGPATCHER11 L"Plik wersji zostanie pobrany."
#define STRINGPATCHER12 L"Pobranie pliku wersji nie powiodło się."
#define STRINGPATCHER13 L"Spróbuj ponownie."
#define STRINGPATCHER14 L"Czytanie pliku wersji nie powiodło się."
#define STRINGPATCHER15 L"Spróbuj ponownie."
#define STRINGPATCHER16 L"Nowa wersja zostanie porównana"
#define STRINGPATCHER17 L"z zainstalowaną wersją."
#define STRINGPATCHER18 L"Porównanie wersji nie powiodło się."
#define STRINGPATCHER19 L"Spróbuj ponownie."
#define STRINGPATCHER20 L"Pobranie pliku patch nie powiodło się."
#define STRINGPATCHER21 L"Spróbuj ponownie."
#define STRINGPATCHER22 L"Instalacja zakończona."
#define STRINGPATCHER23 L"Kliknij na \"Wgraj\", by rozpocząć grę."

#define	STRINGPATCHER35	L""
