#pragma once

#define STRINGMAIN00 L"Please login"
#define STRINGMAIN01 L"from the website."
#define STRINGMAIN02 L"Starting L"
#define STRINGMAIN03 L"Elsword Patch program."
#define STRINGMAIN04 L"Elsword is"
#define STRINGMAIN05 L"already running."
#define STRINGMAIN06 L"Downloading DirectX 9.0c."
#define STRINGMAIN07 L""
#define STRINGMAIN08 L"Unable to download DirectX 9.0c file!"
#define STRINGMAIN09 L"Press \'OK\' button."
#define STRINGMAIN10 L"Installing DirectX 9.0c."
#define STRINGMAIN11 L"Press \'OK\' button."
#define STRINGMAIN12 L"Unable to open the patcher window"
#define STRINGMAIN13 L"Please re-run this program."
#define STRINGMAIN14 L"Do you want to cancel"
#define STRINGMAIN15 L"downloading patches and running Elsword?"
#define STRINGMAIN16 L"Unable to execute the game"
#define STRINGMAIN17 L"Please try again."
#define STRINGMAIN18 L"Do you want to cancel"
#define STRINGMAIN19 L"downloading patches and running Elsword?"
#define STRINGMAIN20 L"Closing the program"
#define STRINGMAIN21 L"Please try again after 30 seconds."
#define STRINGMAIN22 L"Unable to start the game"
#define STRINGMAIN23 L"Please try again."

#define STRINGPATCHER00 L"Unable to update the file version"
#define STRINGPATCHER01 L"Please try again."
#define STRINGPATCHER02 L"Currently patching."
#define STRINGPATCHER03 L"Downloading files from the patch path"
#define STRINGPATCHER04 L"Unable to connect to the patch server"
#define STRINGPATCHER05 L"Please try again."
#define STRINGPATCHER06 L"Unable to download from the file path"
#define STRINGPATCHER07 L"Please try again."
#define STRINGPATCHER08 L"Unable to read from the file path"
#define STRINGPATCHER09 L"Please try again."
#define STRINGPATCHER10 L"Patching in progress."
#define STRINGPATCHER11 L"Downloading the file version"
#define STRINGPATCHER12 L"Unable to download the file version"
#define STRINGPATCHER13 L"Please try again."
#define STRINGPATCHER14 L"Unable to read the file version"
#define STRINGPATCHER15 L"Please try again."
#define STRINGPATCHER16 L"Comparing the new version"
#define STRINGPATCHER17 L"with current installed version."
#define STRINGPATCHER18 L"Unable to compare the versions"
#define STRINGPATCHER19 L"Please try again."
#define STRINGPATCHER20 L"Unable to download patch file"
#define STRINGPATCHER21  L"Please try again."
#define STRINGPATCHER22 L"Installation Completed"
#define STRINGPATCHER23 L"Press \'Play\' button to start the game."

#define	STRINGPATCHER35	L"패치가 완료 되었습니다."
