-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

-- BASE OPTION SETING ------------------------------------------------
-- Grid On/Off : CHECK BOX
CHECK_GRID_X = 10
CHECK_GRID_Y = 10
CHECK_GRID_W = 100
CHECK_GRID_H = 20

-- Wireframe : CHECK BOX
CHECK_WIREFRAME_X = 10
CHECK_WIREFRAME_Y = 31
CHECK_WIREFRAME_W = 105
CHECK_WIREFRAME_H = 20

-- RESET : BUTTON
BUT_RESET_X = 10
BUT_RESET_Y = 52
BUT_RESET_W = 85
BUT_RESET_H = 40

-- UI INIT : BUTTON
BUT_UI_INIT_X = 10
BUT_UI_INIT_Y = 93
BUT_UI_INIT_W = 85
BUT_UI_INIT_H = 30

-- CAMERA MODE : STATIC
STATIC_CAMERA_MODE_X = 120
STATIC_CAMERA_MODE_Y = 10
STATIC_CAMERA_MODE_W = 80
STATIC_CAMERA_MODE_H = 20

-- CAMERA NORMAL MODE : RADIO BUTTON
RADIO_CAMERA_NORMAL_X = 120
RADIO_CAMERA_NORMAL_Y = 31
RADIO_CAMERA_NORMAL_W = 90
RADIO_CAMERA_NORMAL_H = 20

-- RADIO_CAMERA_NAVIGATION
RADIO_CAMERA_NAVIGATION_X = 120
RADIO_CAMERA_NAVIGATION_Y = 52
RADIO_CAMERA_NAVIGATION_W = 90
RADIO_CAMERA_NAVIGATION_H = 20

--BUT_CAMERA_RESET
BUT_CAMERA_RESET_X = 120
BUT_CAMERA_RESET_Y = 73
BUT_CAMERA_RESET_W = 90
BUT_CAMERA_RESET_H = 30

-- BG COLOR : STATIC
STATIC_BG_COLOR_X = 240
STATIC_BG_COLOR_Y = 10
STATIC_BG_COLOR_W = 50
STATIC_BG_COLOR_H = 20

-- BG COLOR A : EDIT BOX
EDIT_BG_A_X = 240
EDIT_BG_A_Y = 31
EDIT_BG_A_W = 50
EDIT_BG_A_H = 30

-- BG COLOR A : STATIC
STATIC_BG_A_X = 291
STATIC_BG_A_Y = 31
STATIC_BG_A_W = 20
STATIC_BG_A_H = 20

-- BG COLOR R : EDIT BOX
EDIT_BG_R_X = 240
EDIT_BG_R_Y = 62
EDIT_BG_R_W = 50
EDIT_BG_R_H = 30
-- BG COLOR R : STATIC
STATIC_BG_R_X = 291
STATIC_BG_R_Y = 62
STATIC_BG_R_W = 20
STATIC_BG_R_H = 20

-- BG COLOR G : EDIT BOX
EDIT_BG_G_X = 240
EDIT_BG_G_Y = 93
EDIT_BG_G_W = 50
EDIT_BG_G_H = 30
-- BG COLOR G : STATIC
STATIC_BG_G_X = 291
STATIC_BG_G_Y = 93
STATIC_BG_G_W = 20
STATIC_BG_G_H = 20

-- BG COLOR B : EDIT BOX
EDIT_BG_B_X = 240
EDIT_BG_B_Y = 124
EDIT_BG_B_W = 50
EDIT_BG_B_H = 30

-- BG COLOR B : STATIC
STATIC_BG_B_X = 291
STATIC_BG_B_Y = 124
STATIC_BG_B_W = 20
STATIC_BG_B_H = 20

--STATIC_WORLD_MESH
STATIC_WORLD_MESH_X = 10
STATIC_WORLD_MESH_Y = 120
STATIC_WORLD_MESH_W = 80
STATIC_WORLD_MESH_H = 20

--BUT_WORLD_MESH
BUT_WORLD_MESH_X = 10
BUT_WORLD_MESH_Y = 141
BUT_WORLD_MESH_W = 150
BUT_WORLD_MESH_H = 30

--BUT_ATTACH_WEAPON
BUT_ATTACH_WEAPON_X = -560
BUT_ATTACH_WEAPON_Y = 340
BUT_ATTACH_WEAPON_W = 100
BUT_ATTACH_WEAPON_H = 20

--EDIT_ATTACH_WEAPON_BONE_NAME
EDIT_ATTACH_WEAPON_BONE_NAME_X = -560
EDIT_ATTACH_WEAPON_BONE_NAME_Y = 300
EDIT_ATTACH_WEAPON_BONE_NAME_W = 120
EDIT_ATTACH_WEAPON_BONE_NAME_H = 35

--STATIC_ATTACH_WEAPON_BONE_NAME
STATIC_ATTACH_WEAPON_BONE_NAME_X = -560
STATIC_ATTACH_WEAPON_BONE_NAME_Y = 270
STATIC_ATTACH_WEAPON_BONE_NAME_W = 100
STATIC_ATTACH_WEAPON_BONE_NAME_H = 30


WEAPON_ROT_POS_X = 140
WEAPON_ROT_WIDTH = 90

--EDIT_WEAPON_ROT_X
EDIT_WEAPON_ROT_X_X = WEAPON_ROT_POS_X
EDIT_WEAPON_ROT_X_Y = 300
EDIT_WEAPON_ROT_X_W = WEAPON_ROT_WIDTH
EDIT_WEAPON_ROT_X_H = 35

--STATIC_WEAPON_ROT_X
STATIC_WEAPON_ROT_X_X = WEAPON_ROT_POS_X
STATIC_WEAPON_ROT_X_Y = 270
STATIC_WEAPON_ROT_X_W = WEAPON_ROT_WIDTH
STATIC_WEAPON_ROT_X_H = 30

--EDIT_WEAPON_ROT_Y
EDIT_WEAPON_ROT_Y_X = WEAPON_ROT_POS_X
EDIT_WEAPON_ROT_Y_Y = 360
EDIT_WEAPON_ROT_Y_W = WEAPON_ROT_WIDTH
EDIT_WEAPON_ROT_Y_H = 35

--STATIC_WEAPON_ROT_Y
STATIC_WEAPON_ROT_Y_X = WEAPON_ROT_POS_X
STATIC_WEAPON_ROT_Y_Y = 330
STATIC_WEAPON_ROT_Y_W = WEAPON_ROT_WIDTH
STATIC_WEAPON_ROT_Y_H = 30

--EDIT_WEAPON_ROT_Z
EDIT_WEAPON_ROT_Z_X = WEAPON_ROT_POS_X
EDIT_WEAPON_ROT_Z_Y = 420
EDIT_WEAPON_ROT_Z_W = WEAPON_ROT_WIDTH
EDIT_WEAPON_ROT_Z_H = 35

--STATIC_WEAPON_ROT_Z
STATIC_WEAPON_ROT_Z_X = WEAPON_ROT_POS_X
STATIC_WEAPON_ROT_Z_Y = 390
STATIC_WEAPON_ROT_Z_W = 100
STATIC_WEAPON_ROT_Z_H = 30





--BUT_WORLD_MESH_RESET
BUT_WORLD_MESH_RESET_X = 87
BUT_WORLD_MESH_RESET_Y = 172
BUT_WORLD_MESH_RESET_W = 80
BUT_WORLD_MESH_RESET_H = 80

--STATIC_WORLD_MESH_X
STATIC_WORLD_MESH_X_X = 10
STATIC_WORLD_MESH_X_Y = 172
STATIC_WORLD_MESH_X_W = 20
STATIC_WORLD_MESH_X_H = 20

--STATIC_WORLD_MESH_Y
STATIC_WORLD_MESH_Y_X = 10
STATIC_WORLD_MESH_Y_Y = 203
STATIC_WORLD_MESH_Y_W = 20
STATIC_WORLD_MESH_Y_H = 20

--STATIC_WORLD_MESH_Z
STATIC_WORLD_MESH_Z_X = 10
STATIC_WORLD_MESH_Z_Y = 234
STATIC_WORLD_MESH_Z_W = 20
STATIC_WORLD_MESH_Z_H = 20

--EDIT_WORLD_MESH_X
EDIT_WORLD_MESH_X_X = 31
EDIT_WORLD_MESH_X_Y = 172
EDIT_WORLD_MESH_X_W = 55
EDIT_WORLD_MESH_X_H = 30

--EDIT_WORLD_MESH_Y
EDIT_WORLD_MESH_Y_X = 31
EDIT_WORLD_MESH_Y_Y = 203
EDIT_WORLD_MESH_Y_W = 55
EDIT_WORLD_MESH_Y_H = 30

--EDIT_WORLD_MESH_Z
EDIT_WORLD_MESH_Z_X = 31
EDIT_WORLD_MESH_Z_Y = 234
EDIT_WORLD_MESH_Z_W = 55
EDIT_WORLD_MESH_Z_H = 30

--BUT_EFFECT_SET
BUT_EFFECT_SET_X = 10
BUT_EFFECT_SET_Y = 380
BUT_EFFECT_SET_W = 100
BUT_EFFECT_SET_H = 30

-- UNIT SETING ------------------------------------------------

-- SCALE : STATIC
STATIC_SCALE_X = 10
STATIC_SCALE_Y = 10
STATIC_SCALE_W = 50
STATIC_SCALE_H = 20

--EDIT_SCALE_X
EDIT_SCALE_X_X = 10
EDIT_SCALE_X_Y = 31
EDIT_SCALE_X_W = 50
EDIT_SCALE_X_H = 30

--STATIC_SCALE_X
STATIC_SCALE_X_X = 60
STATIC_SCALE_X_Y = 31
STATIC_SCALE_X_W = 20
STATIC_SCALE_X_H = 20

--EDIT_SCALE_Y
EDIT_SCALE_Y_X = 10
EDIT_SCALE_Y_Y = 62
EDIT_SCALE_Y_W = 50
EDIT_SCALE_Y_H = 30

--STATIC_SCALE_Y
STATIC_SCALE_Y_X = 60
STATIC_SCALE_Y_Y = 62
STATIC_SCALE_Y_W = 20
STATIC_SCALE_Y_H = 20

--EDIT_SCALE_Z
EDIT_SCALE_Z_X = 10
EDIT_SCALE_Z_Y = 93
EDIT_SCALE_Z_W = 50
EDIT_SCALE_Z_H = 30

--STATIC_SCALE_Z
STATIC_SCALE_Z_X = 60
STATIC_SCALE_Z_Y = 93
STATIC_SCALE_Z_W = 20
STATIC_SCALE_Z_H = 20

-- STATIC_LIGHT_POS : STATIC
STATIC_LIGHT_POS_X = 90
STATIC_LIGHT_POS_Y = 10
STATIC_LIGHT_POS_W = 50
STATIC_LIGHT_POS_H = 20

--EDIT_LIGHT_POS_X
EDIT_LIGHT_POS_X_X = 90
EDIT_LIGHT_POS_X_Y = 31
EDIT_LIGHT_POS_X_W = 70
EDIT_LIGHT_POS_X_H = 30

--STATIC_SLIGHT_POS_X
STATIC_LIGHT_POS_X_X = 161
STATIC_LIGHT_POS_X_Y = 31
STATIC_LIGHT_POS_X_W = 20
STATIC_LIGHT_POS_X_H = 20

--EDIT_LIGHT_POS_Y
EDIT_LIGHT_POS_Y_X = 90
EDIT_LIGHT_POS_Y_Y = 62
EDIT_LIGHT_POS_Y_W = 70
EDIT_LIGHT_POS_Y_H = 30

--STATIC_LIGHT_POS_Y
STATIC_LIGHT_POS_Y_X = 161
STATIC_LIGHT_POS_Y_Y = 62
STATIC_LIGHT_POS_Y_W = 20
STATIC_LIGHT_POS_Y_H = 20

--EDIT_LIGHT_POS_Z
EDIT_LIGHT_POS_Z_X = 90
EDIT_LIGHT_POS_Z_Y = 93
EDIT_LIGHT_POS_Z_W = 70
EDIT_LIGHT_POS_Z_H = 30

--CHECK_LIGHT_ONOFF
CHECK_LIGHT_ONOFF_X = 90
CHECK_LIGHT_ONOFF_Y = 124
CHECK_LIGHT_ONOFF_W = 80
CHECK_LIGHT_ONOFF_H = 20

--STATIC_LIGHT_POS_Z
STATIC_LIGHT_POS_Z_X = 161
STATIC_LIGHT_POS_Z_Y = 93
STATIC_LIGHT_POS_Z_W = 20
STATIC_LIGHT_POS_Z_H = 20

--STATIC_OBJECT
STATIC_OBJECT_X = 250
STATIC_OBJECT_Y = 10
STATIC_OBJECT_W = 55
STATIC_OBJECT_H = 20

--LIST_OBJECT
LIST_OBJECT_X = 250
LIST_OBJECT_Y = 31
LIST_OBJECT_W = 150
LIST_OBJECT_H = 150

--STATIC_ANIMATION
STATIC_ANIMATION_X = 250
STATIC_ANIMATION_Y = 182
STATIC_ANIMATION_W = 70
STATIC_ANIMATION_H = 20

--LIST_ANIMATION
LIST_ANIMATION_X = 250
LIST_ANIMATION_Y = 203
LIST_ANIMATION_W = 150
LIST_ANIMATION_H = 150

--EDIT_ANIM_NUM
EDIT_ANIM_NUM_X = 250
EDIT_ANIM_NUM_Y = 354
EDIT_ANIM_NUM_W = 50
EDIT_ANIM_NUM_H = 30

--EDIT_ANIM_NAME
EDIT_ANIM_NAME_X = 110
EDIT_ANIM_NAME_Y = 200
EDIT_ANIM_NAME_W = 130
EDIT_ANIM_NAME_H = 33

--BUT_ANIM_NAME_CHANGE
BUT_ANIM_NAME_CHANGE_X = 110
BUT_ANIM_NAME_CHANGE_Y = 235
BUT_ANIM_NAME_CHANGE_W = 130
BUT_ANIM_NAME_CHANGE_H = 33

--BUT_PLAY_ONOFF
BUT_PLAY_ONOFF_X = 250
BUT_PLAY_ONOFF_Y = 385
BUT_PLAY_ONOFF_W = 80
BUT_PLAY_ONOFF_H = 30

--STATIC_ANIM_SPEED
STATIC_ANIM_SPEED_X = 330
STATIC_ANIM_SPEED_Y = 350
STATIC_ANIM_SPEED_W = 100
STATIC_ANIM_SPEED_H = 20

--SLIDE_ANIM_SPEED
SLIDE_ANIM_SPEED_X = 330
SLIDE_ANIM_SPEED_Y = 371
SLIDE_ANIM_SPEED_W = 100
SLIDE_ANIM_SPEED_H = 20

--STATIC_ANIM_FRAME
STATIC_ANIM_FRAME_X = 330
STATIC_ANIM_FRAME_Y = 392
STATIC_ANIM_FRAME_W = 100
STATIC_ANIM_FRAME_H = 30

--CHECK_MOTION_ONOFF
CHECK_MOTION_ONOFF_X = 330
CHECK_MOTION_ONOFF_Y = 433
CHECK_MOTION_ONOFF_W = 100
CHECK_MOTION_ONOFF_H = 20

--BUT_RENDER_PARAM
BUT_RENDER_PARAM_X = 330
BUT_RENDER_PARAM_Y = 454
BUT_RENDER_PARAM_W = 100
BUT_RENDER_PARAM_H = 40

--STATIC_PLAY_TYPE
STATIC_PLAY_TYPE_X = 250
STATIC_PLAY_TYPE_Y = 470
STATIC_PLAY_TYPE_W = 80
STATIC_PLAY_TYPE_H = 20

--COMBO_PLAY_TYPE
COMBO_PLAY_TYPE_X = 250
COMBO_PLAY_TYPE_Y = 491
COMBO_PLAY_TYPE_W = 100
COMBO_PLAY_TYPE_H = 25

--CHECK_BOUNDING
CHECK_BOUNDING_X = 250
CHECK_BOUNDING_Y = 530
CHECK_BOUNDING_W = 100
CHECK_BOUNDING_H = 25

--CHECK_ATTACK_BOX
CHECK_ATTACK_BOX_X = 250
CHECK_ATTACK_BOX_Y = 560
CHECK_ATTACK_BOX_W = 100
CHECK_ATTACK_BOX_H = 25


-- UI_EDIT_FRAME_TIME_INC
EDIT_FRAME_TIME_INC_X = 250
EDIT_FRAME_TIME_INC_Y = 590
EDIT_FRAME_TIME_INC_W = 100
EDIT_FRAME_TIME_INC_H = 30


-- UI_BUT_PREV_FRAME
BUT_PREV_FRAME_X = 250
BUT_PREV_FRAME_Y = 630
BUT_PREV_FRAME_W = 50
BUT_PREV_FRAME_H = 25


--UI_BUT_NEXT_FRAME
BUT_NEXT_FRAME_X = 310
BUT_NEXT_FRAME_Y = 630
BUT_NEXT_FRAME_W = 50
BUT_NEXT_FRAME_H = 25




-- Mesh Seting --------------------------------------------------------
-- STATIC_SCALE
STATIC_MESH_SCALE_X = 10
STATIC_MESH_SCALE_Y = 10
STATIC_MESH_SCALE_W = 50
STATIC_MESH_SCALE_H = 20

--EDIT_SCALE_X
EDIT_MESH_SCALE_X_X = 10
EDIT_MESH_SCALE_X_Y = 31
EDIT_MESH_SCALE_X_W = 50
EDIT_MESH_SCALE_X_H = 30

--STATIC_SCALE_X
STATIC_MESH_SCALE_X_X = 60
STATIC_MESH_SCALE_X_Y = 31
STATIC_MESH_SCALE_X_W = 20
STATIC_MESH_SCALE_X_H = 20

--EDIT_SCALE_Y
EDIT_MESH_SCALE_Y_X = 10
EDIT_MESH_SCALE_Y_Y = 62
EDIT_MESH_SCALE_Y_W = 50
EDIT_MESH_SCALE_Y_H = 30

--STATIC_SCALE_Y
STATIC_MESH_SCALE_Y_X = 60
STATIC_MESH_SCALE_Y_Y = 62
STATIC_MESH_SCALE_Y_W = 20
STATIC_MESH_SCALE_Y_H = 20

--EDIT_SCALE_Z
EDIT_MESH_SCALE_Z_X = 10
EDIT_MESH_SCALE_Z_Y = 93
EDIT_MESH_SCALE_Z_W = 50
EDIT_MESH_SCALE_Z_H = 30

--STATIC_SCALE_Z
STATIC_MESH_SCALE_Z_X = 60
STATIC_MESH_SCALE_Z_Y = 93
STATIC_MESH_SCALE_Z_W = 20
STATIC_MESH_SCALE_Z_H = 20

-- STATIC_LIGHT_POS : STATIC
STATIC_MESH_LIGHT_POS_X = 90
STATIC_MESH_LIGHT_POS_Y = 10
STATIC_MESH_LIGHT_POS_W = 50
STATIC_MESH_LIGHT_POS_H = 20

--EDIT_LIGHT_POS_X
EDIT_MESH_LIGHT_POS_X_X = 90
EDIT_MESH_LIGHT_POS_X_Y = 31
EDIT_MESH_LIGHT_POS_X_W = 70
EDIT_MESH_LIGHT_POS_X_H = 30

--STATIC_SLIGHT_POS_X
STATIC_MESH_LIGHT_POS_X_X = 161
STATIC_MESH_LIGHT_POS_X_Y = 31
STATIC_MESH_LIGHT_POS_X_W = 20
STATIC_MESH_LIGHT_POS_X_H = 20

--EDIT_LIGHT_POS_Y
EDIT_MESH_LIGHT_POS_Y_X = 90
EDIT_MESH_LIGHT_POS_Y_Y = 62
EDIT_MESH_LIGHT_POS_Y_W = 70
EDIT_MESH_LIGHT_POS_Y_H = 30

--STATIC_LIGHT_POS_Y
STATIC_MESH_LIGHT_POS_Y_X = 161
STATIC_MESH_LIGHT_POS_Y_Y = 62
STATIC_MESH_LIGHT_POS_Y_W = 20
STATIC_MESH_LIGHT_POS_Y_H = 20

--EDIT_LIGHT_POS_Z
EDIT_MESH_LIGHT_POS_Z_X = 90
EDIT_MESH_LIGHT_POS_Z_Y = 93
EDIT_MESH_LIGHT_POS_Z_W = 70
EDIT_MESH_LIGHT_POS_Z_H = 30

--CHECK_LIGHT_ONOFF
CHECK_MESH_LIGHT_ONOFF_X = 90
CHECK_MESH_LIGHT_ONOFF_Y = 124
CHECK_MESH_LIGHT_ONOFF_W = 80
CHECK_MESH_LIGHT_ONOFF_H = 20

--STATIC_LIGHT_POS_Z
STATIC_MESH_LIGHT_POS_Z_X = 161
STATIC_MESH_LIGHT_POS_Z_Y = 93
STATIC_MESH_LIGHT_POS_Z_W = 20
STATIC_MESH_LIGHT_POS_Z_H = 20

--BUT_RENDER_PARAM
BUT_MESH_RENDER_PARAM_X = 200
BUT_MESH_RENDER_PARAM_Y = 10
BUT_MESH_RENDER_PARAM_W = 100
BUT_MESH_RENDER_PARAM_H = 40

-- RENDER PARAM SETING ------------------------------------------------
--STATIC_RENDERTYPE
STATIC_RENDERTYPE_X = 10
STATIC_RENDERTYPE_Y = 10
STATIC_RENDERTYPE_W = 80
STATIC_RENDERTYPE_H = 20

--COMBO_RENDERTYPE
COMBO_RENDERTYPE_X = 10
COMBO_RENDERTYPE_Y = 31
COMBO_RENDERTYPE_W = 200
COMBO_RENDERTYPE_H = 25

--STATIC_CARTOON_TEX_TYPE
STATIC_CARTOON_TEX_TYPE_X = 10
STATIC_CARTOON_TEX_TYPE_Y = 57
STATIC_CARTOON_TEX_TYPE_W = 130
STATIC_CARTOON_TEX_TYPE_H = 20

--COMBO_CARTOON_TEX_TYPE
COMBO_CARTOON_TEX_TYPE_X = 10
COMBO_CARTOON_TEX_TYPE_Y = 78
COMBO_CARTOON_TEX_TYPE_W = 200
COMBO_CARTOON_TEX_TYPE_H = 25

--STATIC_OUTLINE_WIDE
STATIC_OUTLINE_WIDE_X = 10
STATIC_OUTLINE_WIDE_Y = 443
STATIC_OUTLINE_WIDE_W = 100
STATIC_OUTLINE_WIDE_H = 20

--EDIT_OUTLINE_WIDE
EDIT_OUTLINE_WIDE_X = 10
EDIT_OUTLINE_WIDE_Y = 463
EDIT_OUTLINE_WIDE_W = 100
EDIT_OUTLINE_WIDE_H = 30

--STATIC_OUTLINE_COLOR
STATIC_OUTLINE_COLOR_X = 231
STATIC_OUTLINE_COLOR_Y = 339
STATIC_OUTLINE_COLOR_W = 85
STATIC_OUTLINE_COLOR_H = 20

--STATIC_OUTLINE_COLOR_A
STATIC_OUTLINE_COLOR_A_X = 231
STATIC_OUTLINE_COLOR_A_Y = 360
STATIC_OUTLINE_COLOR_A_W = 20
STATIC_OUTLINE_COLOR_A_H = 20

--STATIC_OUTLINE_COLOR_R
STATIC_OUTLINE_COLOR_R_X = 231
STATIC_OUTLINE_COLOR_R_Y = 391
STATIC_OUTLINE_COLOR_R_W = 20
STATIC_OUTLINE_COLOR_R_H = 20

--STATIC_OUTLINE_COLOR_G
STATIC_OUTLINE_COLOR_G_X = 231
STATIC_OUTLINE_COLOR_G_Y = 422
STATIC_OUTLINE_COLOR_G_W = 20
STATIC_OUTLINE_COLOR_G_H = 20

--STATIC_OUTLINE_COLOR_B
STATIC_OUTLINE_COLOR_B_X = 231
STATIC_OUTLINE_COLOR_B_Y = 453
STATIC_OUTLINE_COLOR_B_W = 20
STATIC_OUTLINE_COLOR_B_H = 20

--EDIT_OUTLINE_COLOR_A
EDIT_OUTLINE_COLOR_A_X = 252
EDIT_OUTLINE_COLOR_A_Y = 360
EDIT_OUTLINE_COLOR_A_W = 50
EDIT_OUTLINE_COLOR_A_H = 30

--EDIT_OUTLINE_COLOR_R
EDIT_OUTLINE_COLOR_R_X = 252
EDIT_OUTLINE_COLOR_R_Y = 391
EDIT_OUTLINE_COLOR_R_W = 50
EDIT_OUTLINE_COLOR_R_H = 30

--EDIT_OUTLINE_COLOR_G
EDIT_OUTLINE_COLOR_G_X = 252
EDIT_OUTLINE_COLOR_G_Y = 422
EDIT_OUTLINE_COLOR_G_W = 50
EDIT_OUTLINE_COLOR_G_H = 30

--EDIT_OUTLINE_COLOR_B
EDIT_OUTLINE_COLOR_B_X = 252
EDIT_OUTLINE_COLOR_B_Y = 453
EDIT_OUTLINE_COLOR_B_W = 50
EDIT_OUTLINE_COLOR_B_H = 30

--STATIC_COLOR
STATIC_COLOR_X = 320
STATIC_COLOR_Y = 339
STATIC_COLOR_W = 50
STATIC_COLOR_H = 20

--STATIC_COLOR_A
STATIC_COLOR_A_X = 320
STATIC_COLOR_A_Y = 360
STATIC_COLOR_A_W = 20
STATIC_COLOR_A_H = 20

--STATIC_COLOR_R
STATIC_COLOR_R_X = 320
STATIC_COLOR_R_Y = 391
STATIC_COLOR_R_W = 20
STATIC_COLOR_R_H = 20

--STATIC_COLOR_G
STATIC_COLOR_G_X = 320
STATIC_COLOR_G_Y = 422
STATIC_COLOR_G_W = 20
STATIC_COLOR_G_H = 20

--STATIC_COLOR_B
STATIC_COLOR_B_X = 320
STATIC_COLOR_B_Y = 453
STATIC_COLOR_B_W = 20
STATIC_COLOR_B_H = 20

--EDIT_COLOR_A
EDIT_COLOR_A_X = 341
EDIT_COLOR_A_Y = 360
EDIT_COLOR_A_W = 50
EDIT_COLOR_A_H = 30

--EDIT_COLOR_R
EDIT_COLOR_R_X = 341
EDIT_COLOR_R_Y = 391
EDIT_COLOR_R_W = 50
EDIT_COLOR_R_H = 30

--EDIT_COLOR_G
EDIT_COLOR_G_X = 341
EDIT_COLOR_G_Y = 422
EDIT_COLOR_G_W = 50
EDIT_COLOR_G_H = 30

--EDIT_COLOR_B
EDIT_COLOR_B_X = 341
EDIT_COLOR_B_Y = 453
EDIT_COLOR_B_W = 50
EDIT_COLOR_B_H = 30

--STATIC_LIGHTFLOW_WIDE
STATIC_LIGHTFLOW_WIDE_X = 115
STATIC_LIGHTFLOW_WIDE_Y = 442
STATIC_LIGHTFLOW_WIDE_W = 120
STATIC_LIGHTFLOW_WIDE_H = 20

--EDIT_LIGHTFLOW_WIDE
EDIT_LIGHTFLOW_WIDE_X = 115
EDIT_LIGHTFLOW_WIDE_Y = 463
EDIT_LIGHTFLOW_WIDE_W = 100
EDIT_LIGHTFLOW_WIDE_H = 30

--STATIC_LIGHTFLOW_IMPACT
STATIC_LIGHTFLOW_IMPACT_X = 10
STATIC_LIGHTFLOW_IMPACT_Y = 350
STATIC_LIGHTFLOW_IMPACT_W = 120
STATIC_LIGHTFLOW_IMPACT_H = 20

--STATIC_LIGHTFLOW_IMPACT_MIN
STATIC_LIGHTFLOW_IMPACT_MIN_X = 10
STATIC_LIGHTFLOW_IMPACT_MIN_Y = 371
STATIC_LIGHTFLOW_IMPACT_MIN_W = 40
STATIC_LIGHTFLOW_IMPACT_MIN_H = 20

--STATIC_LIGHTFLOW_IMPACT_MAX
STATIC_LIGHTFLOW_IMPACT_MAX_X = 75
STATIC_LIGHTFLOW_IMPACT_MAX_Y = 371
STATIC_LIGHTFLOW_IMPACT_MAX_W = 40
STATIC_LIGHTFLOW_IMPACT_MAX_H = 20

--STATIC_LIGHTFLOW_IMPACT_ANIMTIME
STATIC_LIGHTFLOW_IMPACT_ANIMTIME_X = 140
STATIC_LIGHTFLOW_IMPACT_ANIMTIME_Y = 371
STATIC_LIGHTFLOW_IMPACT_ANIMTIME_W = 60
STATIC_LIGHTFLOW_IMPACT_ANIMTIME_H = 20

--EDIT_LIGHTFLOW_IMPACT_MIN
EDIT_LIGHTFLOW_IMPACT_MIN_X = 10
EDIT_LIGHTFLOW_IMPACT_MIN_Y = 392
EDIT_LIGHTFLOW_IMPACT_MIN_W = 60
EDIT_LIGHTFLOW_IMPACT_MIN_H = 30

--EDIT_LIGHTFLOW_IMPACT_MAX
EDIT_LIGHTFLOW_IMPACT_MAX_X = 75
EDIT_LIGHTFLOW_IMPACT_MAX_Y = 392
EDIT_LIGHTFLOW_IMPACT_MAX_W = 60
EDIT_LIGHTFLOW_IMPACT_MAX_H = 30

--EDIT_LIGHTFLOW_IMPACT_ANIMTIME
EDIT_LIGHTFLOW_IMPACT_ANIMTIME_X = 140
EDIT_LIGHTFLOW_IMPACT_ANIMTIME_Y = 392
EDIT_LIGHTFLOW_IMPACT_ANIMTIME_W = 60
EDIT_LIGHTFLOW_IMPACT_ANIMTIME_H = 30

--STATIC_LIGHTFLOW_POINT
STATIC_LIGHTFLOW_POINT_X = 395
STATIC_LIGHTFLOW_POINT_Y = 339
STATIC_LIGHTFLOW_POINT_W = 100
STATIC_LIGHTFLOW_POINT_H = 20

--STATIC_LIGHTFLOW_POINT_X
STATIC_LIGHTFLOW_POINT_X_X = 395
STATIC_LIGHTFLOW_POINT_X_Y = 360
STATIC_LIGHTFLOW_POINT_X_W = 20
STATIC_LIGHTFLOW_POINT_X_H = 20

--STATIC_LIGHTFLOW_POINT_Y
STATIC_LIGHTFLOW_POINT_Y_X = 395
STATIC_LIGHTFLOW_POINT_Y_Y = 391
STATIC_LIGHTFLOW_POINT_Y_W = 20
STATIC_LIGHTFLOW_POINT_Y_H = 20

--STATIC_LIGHTFLOW_POINT_Z
STATIC_LIGHTFLOW_POINT_Z_X = 395
STATIC_LIGHTFLOW_POINT_Z_Y = 422
STATIC_LIGHTFLOW_POINT_Z_W = 20
STATIC_LIGHTFLOW_POINT_Z_H = 20

--EDIT_LIGHTFLOW_POINT_X
EDIT_LIGHTFLOW_POINT_X_X = 416
EDIT_LIGHTFLOW_POINT_X_Y = 360
EDIT_LIGHTFLOW_POINT_X_W = 80
EDIT_LIGHTFLOW_POINT_X_H = 30

--EDIT_LIGHTFLOW_POINT_Y
EDIT_LIGHTFLOW_POINT_Y_X = 416
EDIT_LIGHTFLOW_POINT_Y_Y = 391
EDIT_LIGHTFLOW_POINT_Y_W = 80
EDIT_LIGHTFLOW_POINT_Y_H = 30

--EDIT_LIGHTFLOW_POINT_Z
EDIT_LIGHTFLOW_POINT_Z_X = 416
EDIT_LIGHTFLOW_POINT_Z_Y = 422
EDIT_LIGHTFLOW_POINT_Z_W = 80
EDIT_LIGHTFLOW_POINT_Z_H = 30

--STATIC_TEXOFFSET_STAGE0
STATIC_TEXOFFSET_STAGE0_X = 215
STATIC_TEXOFFSET_STAGE0_Y = 10
STATIC_TEXOFFSET_STAGE0_W = 150
STATIC_TEXOFFSET_STAGE0_H = 20

--STATIC_TEXOFFSET_STAGE0_X
STATIC_TEXOFFSET_STAGE0_X_X = 215
STATIC_TEXOFFSET_STAGE0_X_Y = 51
STATIC_TEXOFFSET_STAGE0_X_W = 20
STATIC_TEXOFFSET_STAGE0_X_H = 20

--STATIC_TEXOFFSET_STAGE0_Y
STATIC_TEXOFFSET_STAGE0_Y_X = 215
STATIC_TEXOFFSET_STAGE0_Y_Y = 82
STATIC_TEXOFFSET_STAGE0_Y_W = 20
STATIC_TEXOFFSET_STAGE0_Y_H = 20

--STATIC_TEXOFFSET_STAGE0_MIN
STATIC_TEXOFFSET_STAGE0_MIN_X = 235
STATIC_TEXOFFSET_STAGE0_MIN_Y = 31
STATIC_TEXOFFSET_STAGE0_MIN_W = 40
STATIC_TEXOFFSET_STAGE0_MIN_H = 20

--STATIC_TEXOFFSET_STAGE0_MAX
STATIC_TEXOFFSET_STAGE0_MAX_X = 296
STATIC_TEXOFFSET_STAGE0_MAX_Y = 31
STATIC_TEXOFFSET_STAGE0_MAX_W = 40
STATIC_TEXOFFSET_STAGE0_MAX_H = 20

--STATIC_TEXOFFSET_STAGE0_ANIMTIME
STATIC_TEXOFFSET_STAGE0_ANIMTIME_X = 357
STATIC_TEXOFFSET_STAGE0_ANIMTIME_Y = 31
STATIC_TEXOFFSET_STAGE0_ANIMTIME_W = 60
STATIC_TEXOFFSET_STAGE0_ANIMTIME_H = 20

--EDIT_TEXOFFSET_STAGE0_MIN_X
EDIT_TEXOFFSET_STAGE0_MIN_X_X = 236
EDIT_TEXOFFSET_STAGE0_MIN_X_Y = 51
EDIT_TEXOFFSET_STAGE0_MIN_X_W = 60
EDIT_TEXOFFSET_STAGE0_MIN_X_H = 30

--EDIT_TEXOFFSET_STAGE0_MIN_Y
EDIT_TEXOFFSET_STAGE0_MIN_Y_X = 236
EDIT_TEXOFFSET_STAGE0_MIN_Y_Y = 82
EDIT_TEXOFFSET_STAGE0_MIN_Y_W = 60
EDIT_TEXOFFSET_STAGE0_MIN_Y_H = 30

--EDIT_TEXOFFSET_STAGE0_MAX_X
EDIT_TEXOFFSET_STAGE0_MAX_X_X = 297
EDIT_TEXOFFSET_STAGE0_MAX_X_Y = 51
EDIT_TEXOFFSET_STAGE0_MAX_X_W = 60
EDIT_TEXOFFSET_STAGE0_MAX_X_H = 30

--EDIT_TEXOFFSET_STAGE0_MAX_Y
EDIT_TEXOFFSET_STAGE0_MAX_Y_X = 297
EDIT_TEXOFFSET_STAGE0_MAX_Y_Y = 82
EDIT_TEXOFFSET_STAGE0_MAX_Y_W = 60
EDIT_TEXOFFSET_STAGE0_MAX_Y_H = 30

--EDIT_TEXOFFSET_STAGE0_ANIMTIME
EDIT_TEXOFFSET_STAGE0_ANIMTIME_X = 358
EDIT_TEXOFFSET_STAGE0_ANIMTIME_Y = 51
EDIT_TEXOFFSET_STAGE0_ANIMTIME_W = 60
EDIT_TEXOFFSET_STAGE0_ANIMTIME_H = 30

--STATIC_TEXOFFSET_STAGE1
STATIC_TEXOFFSET_STAGE1_X = 215
STATIC_TEXOFFSET_STAGE1_Y = 113
STATIC_TEXOFFSET_STAGE1_W = 150
STATIC_TEXOFFSET_STAGE1_H = 20

--STATIC_TEXOFFSET_STAGE1_X
STATIC_TEXOFFSET_STAGE1_X_X = 215
STATIC_TEXOFFSET_STAGE1_X_Y = 155
STATIC_TEXOFFSET_STAGE1_X_W = 20
STATIC_TEXOFFSET_STAGE1_X_H = 20

--STATIC_TEXOFFSET_STAGE1_Y
STATIC_TEXOFFSET_STAGE1_Y_X = 215
STATIC_TEXOFFSET_STAGE1_Y_Y = 186
STATIC_TEXOFFSET_STAGE1_Y_W = 20
STATIC_TEXOFFSET_STAGE1_Y_H = 20

--STATIC_TEXOFFSET_STAGE1_MIN
STATIC_TEXOFFSET_STAGE1_MIN_X = 235
STATIC_TEXOFFSET_STAGE1_MIN_Y = 134
STATIC_TEXOFFSET_STAGE1_MIN_W = 40
STATIC_TEXOFFSET_STAGE1_MIN_H = 20

--STATIC_TEXOFFSET_STAGE1_MAX
STATIC_TEXOFFSET_STAGE1_MAX_X = 296
STATIC_TEXOFFSET_STAGE1_MAX_Y = 134
STATIC_TEXOFFSET_STAGE1_MAX_W = 40
STATIC_TEXOFFSET_STAGE1_MAX_H = 20

--STATIC_TEXOFFSET_STAGE1_ANIMTIME
STATIC_TEXOFFSET_STAGE1_ANIMTIME_X = 357
STATIC_TEXOFFSET_STAGE1_ANIMTIME_Y = 134
STATIC_TEXOFFSET_STAGE1_ANIMTIME_W = 60
STATIC_TEXOFFSET_STAGE1_ANIMTIME_H = 20

--EDIT_TEXOFFSET_STAGE1_MIN_X
EDIT_TEXOFFSET_STAGE1_MIN_X_X = 235
EDIT_TEXOFFSET_STAGE1_MIN_X_Y = 155
EDIT_TEXOFFSET_STAGE1_MIN_X_W = 60
EDIT_TEXOFFSET_STAGE1_MIN_X_H = 30

--EDIT_TEXOFFSET_STAGE1_MIN_Y
EDIT_TEXOFFSET_STAGE1_MIN_Y_X = 235
EDIT_TEXOFFSET_STAGE1_MIN_Y_Y = 186
EDIT_TEXOFFSET_STAGE1_MIN_Y_W = 60
EDIT_TEXOFFSET_STAGE1_MIN_Y_H = 30

--EDIT_TEXOFFSET_STAGE1_MAX_X
EDIT_TEXOFFSET_STAGE1_MAX_X_X = 296
EDIT_TEXOFFSET_STAGE1_MAX_X_Y = 155
EDIT_TEXOFFSET_STAGE1_MAX_X_W = 60
EDIT_TEXOFFSET_STAGE1_MAX_X_H = 30

--EDIT_TEXOFFSET_STAGE1_MAX_Y
EDIT_TEXOFFSET_STAGE1_MAX_Y_X = 296
EDIT_TEXOFFSET_STAGE1_MAX_Y_Y = 186
EDIT_TEXOFFSET_STAGE1_MAX_Y_W = 60
EDIT_TEXOFFSET_STAGE1_MAX_Y_H = 30

--EDIT_TEXOFFSET_STAGE1_ANIMTIME
EDIT_TEXOFFSET_STAGE1_ANIMTIME_X = 357
EDIT_TEXOFFSET_STAGE1_ANIMTIME_Y = 155
EDIT_TEXOFFSET_STAGE1_ANIMTIME_W = 60
EDIT_TEXOFFSET_STAGE1_ANIMTIME_H = 30

--STATIC_TEXOFFSET_STAGE2
STATIC_TEXOFFSET_STAGE2_X = 215
STATIC_TEXOFFSET_STAGE2_Y = 216
STATIC_TEXOFFSET_STAGE2_W = 150
STATIC_TEXOFFSET_STAGE2_H = 20

--STATIC_TEXOFFSET_STAGE2_X
STATIC_TEXOFFSET_STAGE2_X_X = 215
STATIC_TEXOFFSET_STAGE2_X_Y = 258
STATIC_TEXOFFSET_STAGE2_X_W = 20
STATIC_TEXOFFSET_STAGE2_X_H = 20

--STATIC_TEXOFFSET_STAGE2_Y
STATIC_TEXOFFSET_STAGE2_Y_X = 215
STATIC_TEXOFFSET_STAGE2_Y_Y = 289
STATIC_TEXOFFSET_STAGE2_Y_W = 20
STATIC_TEXOFFSET_STAGE2_Y_H = 20

--STATIC_TEXOFFSET_STAGE2_MIN
STATIC_TEXOFFSET_STAGE2_MIN_X = 235
STATIC_TEXOFFSET_STAGE2_MIN_Y = 237
STATIC_TEXOFFSET_STAGE2_MIN_W = 40
STATIC_TEXOFFSET_STAGE2_MIN_H = 20

--STATIC_TEXOFFSET_STAGE2_MAX
STATIC_TEXOFFSET_STAGE2_MAX_X = 296
STATIC_TEXOFFSET_STAGE2_MAX_Y = 237
STATIC_TEXOFFSET_STAGE2_MAX_W = 40
STATIC_TEXOFFSET_STAGE2_MAX_H = 20

--STATIC_TEXOFFSET_STAGE2_ANIMTIME
STATIC_TEXOFFSET_STAGE2_ANIMTIME_X = 357
STATIC_TEXOFFSET_STAGE2_ANIMTIME_Y = 237
STATIC_TEXOFFSET_STAGE2_ANIMTIME_W = 60
STATIC_TEXOFFSET_STAGE2_ANIMTIME_H = 20

--EDIT_TEXOFFSET_STAGE2_MIN_X
EDIT_TEXOFFSET_STAGE2_MIN_X_X = 235
EDIT_TEXOFFSET_STAGE2_MIN_X_Y = 258
EDIT_TEXOFFSET_STAGE2_MIN_X_W = 60
EDIT_TEXOFFSET_STAGE2_MIN_X_H = 30

--EDIT_TEXOFFSET_STAGE2_MIN_Y
EDIT_TEXOFFSET_STAGE2_MIN_Y_X = 235
EDIT_TEXOFFSET_STAGE2_MIN_Y_Y = 289
EDIT_TEXOFFSET_STAGE2_MIN_Y_W = 60
EDIT_TEXOFFSET_STAGE2_MIN_Y_H = 30

--EDIT_TEXOFFSET_STAGE2_MAX_X
EDIT_TEXOFFSET_STAGE2_MAX_X_X = 296
EDIT_TEXOFFSET_STAGE2_MAX_X_Y = 258
EDIT_TEXOFFSET_STAGE2_MAX_X_W = 60
EDIT_TEXOFFSET_STAGE2_MAX_X_H = 30

--EDIT_TEXOFFSET_STAGE2_MAX_Y
EDIT_TEXOFFSET_STAGE2_MAX_Y_X = 296
EDIT_TEXOFFSET_STAGE2_MAX_Y_Y = 289
EDIT_TEXOFFSET_STAGE2_MAX_Y_W = 60
EDIT_TEXOFFSET_STAGE2_MAX_Y_H = 30

--EDIT_TEXOFFSET_STAGE2_ANIMTIME
EDIT_TEXOFFSET_STAGE2_ANIMTIME_X = 357
EDIT_TEXOFFSET_STAGE2_ANIMTIME_Y = 258
EDIT_TEXOFFSET_STAGE2_ANIMTIME_W = 60
EDIT_TEXOFFSET_STAGE2_ANIMTIME_H = 30

--STATIC_ALPHA_BLEND
STATIC_ALPHA_BLEND_X = 10
STATIC_ALPHA_BLEND_Y = 104
STATIC_ALPHA_BLEND_W = 80
STATIC_ALPHA_BLEND_H = 20

--COMBO_ALPHA_BLEND
COMBO_ALPHA_BLEND_X = 10
COMBO_ALPHA_BLEND_Y = 125
COMBO_ALPHA_BLEND_W = 200
COMBO_ALPHA_BLEND_H = 25

--STATIC_ZENABLE
STATIC_ZENABLE_X = 10
STATIC_ZENABLE_Y = 151
STATIC_ZENABLE_W = 50
STATIC_ZENABLE_H = 20

--COMBO_ZENABLE
COMBO_ZENABLE_X = 10
COMBO_ZENABLE_Y = 172
COMBO_ZENABLE_W = 200
COMBO_ZENABLE_H = 25

--STATIC_CULLMODE
STATIC_CULLMODE_X = 10
STATIC_CULLMODE_Y = 198
STATIC_CULLMODE_W = 70
STATIC_CULLMODE_H = 20

--COMBO_CULLMODE
COMBO_CULLMODE_X = 10
COMBO_CULLMODE_Y = 219
COMBO_CULLMODE_W = 200
COMBO_CULLMODE_H = 25

--STATIC_SRCBLEND
STATIC_SRCBLEND_X = 10
STATIC_SRCBLEND_Y = 245
STATIC_SRCBLEND_W = 70
STATIC_SRCBLEND_H = 20

--COMBO_SRCBLEND
COMBO_SRCBLEND_X = 10
COMBO_SRCBLEND_Y = 266
COMBO_SRCBLEND_W = 200
COMBO_SRCBLEND_H = 25

--STATIC_DESTBLEND
STATIC_DESTBLEND_X = 10
STATIC_DESTBLEND_Y = 292
STATIC_DESTBLEND_W = 70
STATIC_DESTBLEND_H = 20

--COMBO_DESTBLEND
COMBO_DESTBLEND_X = 10
COMBO_DESTBLEND_Y = 313
COMBO_DESTBLEND_W = 200
COMBO_DESTBLEND_H = 25

--BUT_PARAM_OK
BUT_PARAM_OK_X = 500
BUT_PARAM_OK_Y = 250
BUT_PARAM_OK_W = 100
BUT_PARAM_OK_H = 50

--BUT_PARAM_CANCEL
BUT_PARAM_CANCEL_X = 500
BUT_PARAM_CANCEL_Y = 301
BUT_PARAM_CANCEL_W = 100
BUT_PARAM_CANCEL_H = 50--BUT_ATTACH_WEAPON
BUT_ATTACH_WEAPON_X = 10
BUT_ATTACH_WEAPON_Y = 270 
BUT_ATTACH_WEAPON_W = 100
BUT_ATTACH_WEAPON_H = 20

--EDIT_ATTACH_WEAPON_BONE_NAME
EDIT_ATTACH_WEAPON_BONE_NAME_X = 10
EDIT_ATTACH_WEAPON_BONE_NAME_Y = 310
EDIT_ATTACH_WEAPON_BONE_NAME_W = 120
EDIT_ATTACH_WEAPON_BONE_NAME_H = 32

--STATIC_ATTACH_WEAPON_BONE_NAME
STATIC_ATTACH_WEAPON_BONE_NAME_X = 10
STATIC_ATTACH_WEAPON_BONE_NAME_Y = 290 
STATIC_ATTACH_WEAPON_BONE_NAME_W = 100
STATIC_ATTACH_WEAPON_BONE_NAME_H = 20

--BUT_ATTACH_ACCESSORY
BUT_ATTACH_ACCESSORY_X = 10
BUT_ATTACH_ACCESSORY_Y = 470
BUT_ATTACH_ACCESSORY_W = 100
BUT_ATTACH_ACCESSORY_H = 20

--EDIT_ATTACH_ACCESSORY_BONE_NAME
EDIT_ATTACH_ACCESSORY_BONE_NAME_X = 10
EDIT_ATTACH_ACCESSORY_BONE_NAME_Y = 510
EDIT_ATTACH_ACCESSORY_BONE_NAME_W = 120
EDIT_ATTACH_ACCESSORY_BONE_NAME_H = 35

--STATIC_ATTACH_ACCESSORY_BONE_NAME
STATIC_ATTACH_ACCESSORY_BONE_NAME_X = 10
STATIC_ATTACH_ACCESSORY_BONE_NAME_Y = 490
STATIC_ATTACH_ACCESSORY_BONE_NAME_W = 100
STATIC_ATTACH_ACCESSORY_BONE_NAME_H = 30

ACCESSORY_TRANS_POS_X = 140
ACCESSORY_TRANS_WIDTH = 90

--EDIT_ACCESSORY_ROT_X
EDIT_ACCESSORY_TRANS_X_X = ACCESSORY_TRANS_POS_X
EDIT_ACCESSORY_TRANS_X_Y = 500
EDIT_ACCESSORY_TRANS_X_W = ACCESSORY_TRANS_WIDTH
EDIT_ACCESSORY_TRANS_X_H = 35

--STATIC_ACCESSORY_TRANS_X
STATIC_ACCESSORY_TRANS_X_X = ACCESSORY_TRANS_POS_X - 20
STATIC_ACCESSORY_TRANS_X_Y = 470
STATIC_ACCESSORY_TRANS_X_W = 120
STATIC_ACCESSORY_TRANS_X_H = 30

--EDIT_ACCESSORY_TRANS_Y
EDIT_ACCESSORY_TRANS_Y_X = ACCESSORY_TRANS_POS_X
EDIT_ACCESSORY_TRANS_Y_Y = 560
EDIT_ACCESSORY_TRANS_Y_W = ACCESSORY_TRANS_WIDTH
EDIT_ACCESSORY_TRANS_Y_H = 35

--STATIC_ACCESSORY_TRANS_Y
STATIC_ACCESSORY_TRANS_Y_X = ACCESSORY_TRANS_POS_X - 20
STATIC_ACCESSORY_TRANS_Y_Y = 530
STATIC_ACCESSORY_TRANS_Y_W = 120
STATIC_ACCESSORY_TRANS_Y_H = 30

--EDIT_ACCESSORY_TRANS_Z
EDIT_ACCESSORY_TRANS_Z_X = ACCESSORY_TRANS_POS_X
EDIT_ACCESSORY_TRANS_Z_Y = 620
EDIT_ACCESSORY_TRANS_Z_W = ACCESSORY_TRANS_WIDTH
EDIT_ACCESSORY_TRANS_Z_H = 35

--STATIC_ACCESSORY_TRANS_Z
STATIC_ACCESSORY_TRANS_Z_X = ACCESSORY_TRANS_POS_X - 20
STATIC_ACCESSORY_TRANS_Z_Y = 590
STATIC_ACCESSORY_TRANS_Z_W = 120
STATIC_ACCESSORY_TRANS_Z_H = 30


--STATIC_ACCESSORY_SCALE
STATIC_ACCESSORY_SCALE_X = ACCESSORY_TRANS_POS_X - 140
STATIC_ACCESSORY_SCALE_Y = 540
STATIC_ACCESSORY_SCALE_W = 60
STATIC_ACCESSORY_SCALE_H = 30

--EDIT_ACCESSORY_SCALE_X
EDIT_ACCESSORY_SCALE_X_X = ACCESSORY_TRANS_POS_X - 140
EDIT_ACCESSORY_SCALE_X_Y = 560
EDIT_ACCESSORY_SCALE_X_W = 60
EDIT_ACCESSORY_SCALE_X_H = 30

--EDIT_ACCESSORY_SCALE_Y
EDIT_ACCESSORY_SCALE_Y_X = ACCESSORY_TRANS_POS_X - 140
EDIT_ACCESSORY_SCALE_Y_Y = 600
EDIT_ACCESSORY_SCALE_Y_W = 60
EDIT_ACCESSORY_SCALE_Y_H = 30

--EDIT_ACCESSORY_SCALE_Z
EDIT_ACCESSORY_SCALE_Z_X = ACCESSORY_TRANS_POS_X - 140
EDIT_ACCESSORY_SCALE_Z_Y = 640
EDIT_ACCESSORY_SCALE_Z_W = 60
EDIT_ACCESSORY_SCALE_Z_H = 30

--STATIC_ACCESSORY_ROTATE
STATIC_ACCESSORY_ROTATE_X = ACCESSORY_TRANS_POS_X - 70
STATIC_ACCESSORY_ROTATE_Y = 540
STATIC_ACCESSORY_ROTATE_W = 70
STATIC_ACCESSORY_ROTATE_H = 30

--EDIT_ACCESSORY_ROTATE_X
EDIT_ACCESSORY_ROTATE_X_X = ACCESSORY_TRANS_POS_X - 70
EDIT_ACCESSORY_ROTATE_X_Y = 560
EDIT_ACCESSORY_ROTATE_X_W = 60
EDIT_ACCESSORY_ROTATE_X_H = 30

--EDIT_ACCESSORY_ROTATE_Y
EDIT_ACCESSORY_ROTATE_Y_X = ACCESSORY_TRANS_POS_X - 70
EDIT_ACCESSORY_ROTATE_Y_Y = 600
EDIT_ACCESSORY_ROTATE_Y_W = 60
EDIT_ACCESSORY_ROTATE_Y_H = 30

--EDIT_ACCESSORY_ROTATE_Z
EDIT_ACCESSORY_ROTATE_Z_X = ACCESSORY_TRANS_POS_X - 70
EDIT_ACCESSORY_ROTATE_Z_Y = 640
EDIT_ACCESSORY_ROTATE_Z_W = 60
EDIT_ACCESSORY_ROTATE_Z_H = 30

--LIST_BONE
LIST_BONE_X = -200
LIST_BONE_Y = 30
LIST_BONE_W = 200
LIST_BONE_H = 200