<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="11.0.0-preview.7.26381.103" />
    <PackageVersion Include="SQLitePCLRaw.config.e_sqlite3" Version="3.0.5" />
    <PackageVersion Include="SourceGear.sqlite3" Version="3.53.4" />
  </ItemGroup>
</Project>
