<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>KncWX2Server.Persistence</RootNamespace>
    <AssemblyName>KncWX2Server.Persistence</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../KncWX2Server.Core/KncWX2Server.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLitePCLRaw.config.e_sqlite3" />
    <PackageReference Include="SourceGear.sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Migrations/001_initial.sql" LogicalName="KncWX2Server.Persistence.Migrations.001_initial.sql" />
    <EmbeddedResource Update="Migrations/002_gup_create_unit_schema.sql" LogicalName="KncWX2Server.Persistence.Migrations.002_gup_create_unit_schema.sql" />
    <EmbeddedResource Update="Migrations/003_fix_gunit_nickname_schema.sql" LogicalName="KncWX2Server.Persistence.Migrations.003_fix_gunit_nickname_schema.sql" />
    <EmbeddedResource Update="Migrations/004_gup_delete_unit_schema.sql" LogicalName="KncWX2Server.Persistence.Migrations.004_gup_delete_unit_schema.sql" />
  </ItemGroup>
</Project>
