using KncWX2Server.Core.Common.Routing;

namespace KncWX2Server.Core.Common.Routing;

/// <summary>Exact ePerformerID values present in the 2014 KncSend.h build.</summary>
public enum PerformerId : int
{
    GsProxy = (int)(PerformerRouting.ServerClassClient | PerformerRouting.PerformerProxy),

    GsUser = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerUser),
    GsCharacter = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerCharacter),
    GsServer = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerServer),
    GsServerSame = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerServer | PerformerRouting.SameServerGroupSendType),
    GsGameDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerGameDb),
    GsAccountDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerAccountDb),
    GsLogDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerLogDb),
    GsSmsDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerSmsDb),
    GsNxWebDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerNxWebDb),
    CnProxy = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerProxy),
    LoginProxy = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerProxy),
    GlobalProxy = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerProxy),
    GsNxBilling = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerNxBilling),
    GsNxBillingTcp = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerNxBillingTcp),
    GsField = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerRoom),
    GsParty = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerParty),
    GsNxSoap = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerNxSoap),
    GsGameDb2nd = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerGameDb2nd),
    GsLogDb2nd = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerLogDb2nd),
    GsChatLogDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerChatLogDb),
    GsKogBillingManager = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerKogBillingManager),
    GsKogBillingDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerKogBillingDb),
    GsPublisherAuth = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerPublisherAuth),
    GsPublisherBilling = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerPublisherBilling),
    GsPublisherBillingDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerPublisherBillingDb),
    GsIdPublisherPcbangDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerIdPublisherPcbangAuthDb),
    GsJpRelayDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerJpRelayDb),
    GsEventDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerEventDb),
    GsScriptDb = (int)(PerformerRouting.ServerClassGame | PerformerRouting.PerformerScriptDb),

    CnUser = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerUser),
    CnServer = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerServer),
    CnRoom = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerRoom),
    CnParty = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerParty),
    CnAccountDb = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerAccountDb),
    CnGameDb = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerGameDb),
    CnLogDb = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerLogDb),
    CnSmsDb = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerSmsDb),
    CnEventDb = (int)(PerformerRouting.ServerClassCenter | PerformerRouting.PerformerEventDb),

    LoginUser = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerUser),
    LoginServer = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerServer),
    LoginRoom = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerRoom),
    LoginAccountDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerAccountDb),
    LoginGameDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerGameDb),
    LoginLogDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerLogDb),
    LoginSmsDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerSmsDb),
    LoginNxAuth = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerNxAuth),
    LoginNxWebDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerNxWebDb),
    LoginEventDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerEventDb),
    LoginKogBillingManager = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerKogBillingManager),
    LoginKogBillingDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerKogBillingDb),
    LoginPublisherAuth = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerPublisherAuth),
    LoginPublisherBilling = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerPublisherBilling),
    LoginPublisherBillingDb = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerPublisherBillingDb),
    LoginGiantAuth = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerGiantAuth),
    LoginGiantRoleRegistration = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerGiantRoleRegistration),
    LoginGiantInfo = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerGiantInfo),
    LoginGiantBilling = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerGiantBilling),
    LoginGiantCoupon = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerGiantCoupon),
    LoginAsOtpThread = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerAsOtpThread),
    LoginGarenaBilling = (int)(PerformerRouting.ServerClassLogin | PerformerRouting.PerformerPublisherBilling),

    ChannelUser = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerUser),
    ChannelServer = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerServer),
    ChannelLogDb = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerLogDb),
    ChannelAccountDb = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerAccountDb),
    ChannelLoginProxy = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerProxy),
    ChannelSmsDb = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerSmsDb),
    ChannelGameDb = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerGameDb),
    ChannelEventDb = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerEventDb),
    ChannelAuthDb = (int)(PerformerRouting.ServerClassChannel | PerformerRouting.PerformerPublisherAuthDb),

    GlobalUser = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerUser),
    GlobalServer = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerServer),
    GlobalMatchMaking = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerMatchMaking),
    GlobalAutoParty = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerAutoParty),
    GlobalGameDb = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerGameDb),
    GlobalLogDb = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerLogDb),
    GlobalSmsDb = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerSmsDb),
    GlobalAccountDb = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerAccountDb),
    GlobalNxGmtoolTcp = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerNxGmtoolTcp),
    GlobalEventDb = (int)(PerformerRouting.ServerClassGlobal | PerformerRouting.PerformerEventDb),

    AccountDb = (int)PerformerRouting.PerformerAccountDb,
    LogDb = (int)PerformerRouting.PerformerLogDb,
    EventDb = (int)PerformerRouting.PerformerEventDb,
    ScriptDb = (int)PerformerRouting.PerformerScriptDb,
    Null = -1,
}
