#pragma once


enum PROPERTY_ID
{
	PI_EL_VERTEX_GROUP = 50,	/// 정점 그룹
	PI_EL_VERTEX_X,				/// 정점 X
	PI_EL_VERTEX_Y,				/// 정점 Y
	PI_EL_VERTEX_Z,				/// 정점 Z

	PI_EL_LAND_HEIGHT = 100,	/// 땅 높이

#pragma region Line
	PL_EL_LINE_ATTRIBUTE_1,		/// 라인 속성
	PI_EL_LINE_TYPE,			/// 라인 형식
	PI_EL_LINE_JUMP_DIR,		/// JUMP_UP_REL일 경우 방향 지정
	PI_EL_KEY_LOCK_TIME,		/// 강제 점프 시 키 잠금 효과 지속 시간
	PI_EL_BEFORE_LINE,			/// 이전 라인
	PI_EL_NEXT_LINE,			/// 다음 라인
	PI_EL_LINE_SET,				/// 라인 세트
	PI_EL_START_POS_GROUP,		/// 시작 위치 그룹
	PI_EL_START_POS_X,			/// 시작 위치 X
	PI_EL_START_POS_Y,			/// 시작 위치 Y
	PI_EL_START_POS_Z,			/// 시작 위치 Z
	PI_EL_END_POS_GROUP,		/// 끝 위치 그룹
	PI_EL_END_POS_X,			/// 끝 위치 X
	PI_EL_END_POS_Y,			/// 끝 위치 Y
	PI_EL_END_POS_Z,			/// 끝 위치 Z
#pragma endregion 위치 값

#pragma region Line
	PL_EL_LINE_ATTRIBUTE_2,		/// 라인 속성 2
	PI_EL_TELEPORT_LINE,		/// 순간이동 라인
	PI_EL_CAMERA_ID,			/// 카메라
	PI_EL_TRIGGER_ID,			/// 트리거
	PI_EL_TRIGGER_ON_LINE,		/// 라인 위인가?
#pragma endregion 특수 속성

#pragma region Line
	PL_EL_LINE_ATTRIBUTE_3,		/// 라인 속성 3
	PI_EL_ENABLE,				/// 활성화
	PI_EL_CAN_DOWN,				/// 내려갈 수 있는가?
	PI_EL_CAN_PASS,				/// 통과가능한가?
	PI_EL_ENABLE_WALL_JUMP,		/// 벽 활성화
	PI_EL_MONSTER_ALLOWED,		/// 몬스트
	PI_EL_OTHER_ROAD_UP,
#pragma endregion 기본 속성

#pragma region Line
	PL_EL_LINE_ATTRIBUTE_4,		/// 라인 속성 4
	PI_EL_DUST_TYPE,			/// 먼지 유형
	PI_EL_STOP_FACTOR,			/// 멈춤 인자
	PI_EL_SPEED,				/// 속도
	PI_EL_JUMP_SPEED_X,			/// 점프 속도 X
	PI_EL_JUMP_SPEED_Y,			/// 점프 속도 Y
	PI_EL_CLIFF_HEIGHT,			/// 절벽 높이
#pragma endregion 물리 속성

#pragma region Line
	PL_EL_LINE_ATTRIBUTE_5,			/// 라인 속성 5
	PI_EL_UNDER_WATER,				/// 물속
	PI_EL_UNDERWATER_HEIGHT,		/// 물 높이
	PI_EL_UNDERWATER_BUOYANCY,		/// 부력
	PI_EL_UNDERWATER_RESISTANCE,	/// 물 저향
	PI_EL_UNDERWATER_ANIMSPEED,		/// 애니메이션 속도
	PI_EL_UNDERWATER_VARIANCE_OXYEN,/// 산소
	PI_EL_UNITCOLOR_GROUP,			/// 유닛 색상
	PI_EL_UNITCOLOR_R,				/// Red
	PI_EL_UNITCOLOR_G,				/// Green
	PI_EL_UNITCOLOR_B,				/// Blue
	PI_EL_FORCE_CHANGE_COLOR,		/// 강제 색상 변경
#pragma endregion 물 속 속성
	
#pragma region World
	PI_EW_ATTRIBUTE_1,
	PI_EW_WORLD_LAYER_TEXTURE,
	PI_EW_WORLD_LAYER_LAYER,
	PI_EW_WORLD_LAYER_BLENDTYPE,
	PI_EW_WORLD_LAYER_POS_X,
	PI_EW_WORLD_LAYER_POS_Y,
	PI_EW_WORLD_LAYER_WIDTH,
	PI_EW_WORLD_LAYER_HEIGHT,
	PI_EW_ATTRIBUTE_COLOR_GROUP,
	PI_EW_WORLD_LAYER_COLOR_R,
	PI_EW_WORLD_LAYER_COLOR_G,
	PI_EW_WORLD_LAYER_COLOR_B,
	PI_EW_WORLD_LAYER_COLOR_A,
	PI_EW_WORLD_LAYER_TEX_U,
	PI_EW_WORLD_LAYER_TEX_V,
	PI_EW_WORLD_LAYER_FEEDBACK_U,
	PI_EW_WORLD_LAYER_FEEDBACK_V,
	PI_EW_WORLD_LAYER_SHOW,
#pragma endregion Layer

#pragma region World
	PI_EW_ATTRIBUTE_2,
	PI_EW_WORLD_FOG_ENABLE,
	PI_EW_WORLD_FOG_NEAR_X,
	PI_EW_WORLD_FOG_FAR_X,
	PI_EW_WORLD_FOG_NEAR_Y,
	PI_EW_WORLD_FOG_FAR_Y,
	PI_EW_WORLD_FOG_COLOR_GROUP,
	PI_EW_WORLD_FOG_COLOR_R,
	PI_EW_WORLD_FOG_COLOR_G,
	PI_EW_WORLD_FOG_COLOR_B,
	PI_EW_WORLD_FOG_DENSITY,
	// WORLDOBJECT/skydome에는 fogenable, density만 필요함
#pragma endregion Fog

#pragma region World
	PI_EW_ATTRIBUTE_3,
	PI_EW_WORLD_CAMERA,
	PI_EW_WORLD_SOUND_NAME,
	PI_EW_WORLD_UNIT_COLOR_GROUP,
	PI_EW_WORLD_UNIT_COLOR_R,
	PI_EW_WORLD_UNIT_COLOR_G,
	PI_EW_WORLD_UNIT_COLOR_B,
	PI_EW_WORLD_COLOR_GROUP,
	PI_EW_WORLD_COLOR_R,
	PI_EW_WORLD_COLOR_G,
	PI_EW_WORLD_COLOR_B,
	PI_EW_WORLD_LIGHT_POS_GROUP,
	PI_EW_WORLD_LIGHT_POS_X,
	PI_EW_WORLD_LIGHT_POS_Y,
	PI_EW_WORLD_LIGHT_POS_Z,
#pragma endregion base

#pragma region World
	PI_EW_ATTRIBUTE_4,
	PI_EW_WORLD_SKYDOME_SHOWOBJECT,
	PI_EW_WORLD_SKYDOME_LAYER,
	PI_EW_WORLD_SKYDOME_POSITION_GROUP,
	PI_EW_WORLD_SKYDOME_POSITION_X,
	PI_EW_WORLD_SKYDOME_POSITION_Y,
	PI_EW_WORLD_SKYDOME_POSITION_Z,
	PI_EW_WORLD_SKYDOME_ROTATION_SPEED,
	PI_EW_WORLD_SKYDOME_TEXUV_SPEED_GROUP,
	PI_EW_WORLD_SKYDOME_TEXUV_SPEED_U,
	PI_EW_WORLD_SKYDOME_TEXUV_SPEED_V,
	PI_EW_RORLD_SKYDOME_VIEW_TRACE,	
	PI_EW_WORLD_SKYDOME_ALPHAOBJECT,
	PI_EW_WORLD_SKYDOME_RENDERTYPE,
	PI_EW_WORLD_SKYDOME_SRCBLEND,
	PI_EW_WORLD_SKYDOME_DESTBLEND,
	PI_EW_WORLD_SKYDOME_USE_WORLDCOLOR,
	PI_EW_WORLD_SKYDOME_COLOR_GROUP,
	PI_EW_WORLD_SKYDOME_COLOR_R,
	PI_EW_WORLD_SKYDOME_COLOR_G,
	PI_EW_WORLD_SKYDOME_COLOR_B,
	PI_EW_WORLD_SKYDOME_COLOR_A,
	PI_EW_WORLD_SKYDOME_FOG,
	PI_EW_WORLD_SKYDOME_FOG_COLOR_GROUP,
	PI_EW_WORLD_SKYDOME_FOG_USEOBJECT,
	PI_EW_WORLD_SKYDOME_FOG_GROUP,
	PI_EW_WORLD_SKYDOME_FOG_COLOR_R,
	PI_EW_WORLD_SKYDOME_FOG_COLOR_G,
	PI_EW_WORLD_SKYDOME_FOG_COLOR_B,
	PI_EW_WORLD_SKYDOME_FOG_NEAR_X,
	PI_EW_WORLD_SKYDOME_FOG_FAR_X,
	PI_EW_WORLD_SKYDOME_FOG_NEAR_Y,
	PI_EW_WORLD_SKYDOME_FOG_FAR_Y,
	PI_EW_WORLD_SKYDOME_FOG_DENSITY,
#pragma endregion SkyDome

	// world selected
	PI_EW_WORLD_SELECTED,

#pragma region World
	PI_EW_ATTRIBUTE_5,
	PI_EW_WORLD_OBJECT_SHOWOBJECT,
	PI_EW_WORLD_OBJECT_FREEZING,
	PI_EW_WORLD_OBJECT_LAYER,
	PI_EW_WORLD_OBJECT_POSITION_GROUP,
	PI_EW_WORLD_OBJECT_POSITION_X,
	PI_EW_WORLD_OBJECT_POSITION_Y,
	PI_EW_WORLD_OBJECT_POSITION_Z,
	PI_EW_WORLD_OBJECT_ROTATION_GROUP,
	PI_EW_WORLD_OBJECT_ROTATION_X,
	PI_EW_WORLD_OBJECT_ROTATION_Y,
	PI_EW_WORLD_OBJECT_ROTATION_Z,
	PI_EW_WORLD_OBJECT_SCALE_GROUP,
	PI_EW_WORLD_OBJECT_SCALE_X,
	PI_EW_WORLD_OBJECT_SCALE_Y,
	PI_EW_WORLD_OBJECT_SCALE_Z,
	PI_EW_WORLD_OBJECT_TEXUV_SPEED_GROUP,
	PI_EW_WORLD_OBJECT_TEXUV_SPEED_U,
	PI_EW_WORLD_OBJECT_TEXUV_SPEED_V,
	PI_EW_WORLD_OBJECT_USE_WORLDCOLOR,
	PI_EW_WORLD_OBJECT_COLOR_GROUP,
	PI_EW_WORLD_OBJECT_COLOR_R,
	PI_EW_WORLD_OBJECT_COLOR_G,
	PI_EW_WORLD_OBJECT_COLOR_B,
	PI_EW_WORLD_OBJECT_COLOR_A,	
	PI_EW_WORLD_OBJECT_FORCESHOW,
	PI_EW_WORLD_OBJECT_CANHIDE,
	PI_EW_WORLD_OBJECT_NOTRENDER_HIDDEN,
	PI_EW_WORLD_OBJECT_HIDE_FAR_DISTANCE,
	PI_EW_WORLD_OBJECT_HIDE_NEAR_DISTANCE,
	PI_EW_WORLD_OBJECT_NONCULL,
	PI_EW_WORLD_OBJECT_BILLBOARD,
	PI_EW_WORLD_OBJECT_ALPHATEST,
	PI_EW_WORLD_OBJECT_ALPHAOBJECT,
	PI_EW_WORLD_OBJECT_RENDERTYPE,
	PI_EW_WORLD_OBJECT_SRCBLEND,
	PI_EW_WORLD_OBJECT_DESTBLEND,

	PI_EW_WORLD_OBJECT_FOG,
	PI_EW_WORLD_OBJECT_FOG_USEOBJECT,
	PI_EW_WORLD_OBJECT_FOG_GROUP,
	PI_EW_WORLD_OBJECT_FOG_COLOR_GROUP,	
	PI_EW_WORLD_OBJECT_FOG_COLOR_R,
	PI_EW_WORLD_OBJECT_FOG_COLOR_G,
	PI_EW_WORLD_OBJECT_FOG_COLOR_B,
	PI_EW_WORLD_OBJECT_FOG_NEAR_X,
	PI_EW_WORLD_OBJECT_FOG_FAR_X,
	PI_EW_WORLD_OBJECT_FOG_NEAR_Y,
	PI_EW_WORLD_OBJECT_FOG_FAR_Y,
	PI_EW_WORLD_OBJECT_FOG_DENSITY,

	PI_EW_WORLD_OBJECT_ANIM_NAME,
	PI_EW_WORLD_OBJECT_ANIM_TYPE,
#pragma endregion Object
	
#pragma region World
	PI_EW_WORLD_PARTICLE_TYPE,
	PI_EW_WORLD_PARTICLE_NAME,
	PI_EW_WORLD_PARTICLE_DELAYTIME,
	PI_EW_WORLD_PARTICLE_CULLCHECK,
	PI_EW_WORLD_PARTICLE_PARTICLE_TYPE,	
	PI_EW_WORLD_PARTICLE_TRIGGERITME,
	PI_EW_WORLD_PARTICLE_TRIGGERCOUNT,
	PI_EW_WORLD_PARTICLE_EMITMIN,
	PI_EW_WORLD_PARTICLE_EMITMAX,
	PI_EW_WORLD_PARTICLE_DRAWCOUNT,
	PI_EW_WORLD_PARTICLE_LATENCY,
#pragma endregion Particle
};

enum ENUM_TYPE
{
	ET_LINE_TYPE = 0,
	ET_DUST_TYPE,
	ET_JUMP_DIR,
};

typedef struct 
{
	WCHAR strName[100];
	int inx;
} EnumStringTable;
