#pragma once

enum
{	
	eESD_PID_CS_LAUNCH = 0,
	eESD_PID_CS_LAUNCH_CO,
	eESD_PID_CS_LAUNCH_LG,
	eESD_PID_CS_LAUNCH_CH,
	eESD_PID_CS_SVN_UPDATE,
	eESD_PID_CS_SHUTDOWN,
	eESD_PID_CS_HSB_UPDATE,
	eESD_PID_CS_WINDOWS_UPDATE,
	eESD_PID_CS_VIRUS_CHECK,
	eESD_PID_CS_DBCONNECTION_IDPW,
	
	eESD_PID_SC_STATUS,
	eESD_PID_SC_LG_CRASH,
	eESD_PID_SC_CN_CRASH,
	eESD_PID_SC_GS_CRASH,
	eESD_PID_SC_CH_CRASH,

	eESD_PID_SHUTDOWN_CODE = 64246000,

	eESD_PID_MAX,
};