//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by X2WorldTool.rc
//
#define IDI_MAIN_ICON                   101
#define IDD_DIALOG1                     113
#define IDD_DIALOG2                     114
#define IDD_DIALOG3                     116
#define IDD_DIALOG4                     120
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_EDIT6                       1005
#define IDC_EDIT7                       1006
#define IDC_EDIT8                       1007
#define LM_IDC_EDIT9                    1008
#define LM_IDC_EDIT10                   1009
#define IDC_COMBO1                      1010
#define T_EDIT_LINE_SPEED               1010
#define IDC_LIST2                       1011
#define LM_IDC_COMBO3                   1011
#define IDC_COMBO2                      1012
#define LM_IDC_EDIT11                   1012
#define IDC_STATIC_TEXNAME              1013
#define LM_IDC_EDIT12                   1013
#define T_LIST_DATA                     1014
#define LM_IDC_EDIT13                   1015
#define IDC_SLIDER2                     1016
#define LM_IDC_EDIT14                   1016
#define IDC_SLIDER3                     1017
#define LM_IDC_EDIT15                   1017
#define IDC_SLIDER4                     1018
#define LM_IDC_EDIT16                   1018
#define IDC_STATIC_RED                  1019
#define LM_IDC_EDIT17                   1019
#define IDC_STATIC_GREEN                1020
#define LM_IDC_EDIT18                   1020
#define IDC_STATIC_BLUE                 1021
#define LM_IDC_EDIT19                   1021
#define IDC_BUTTON1                     1022
#define T_LIST_MESH                     1022
#define IDC_BUTTON2                     1023
#define T_LIST_LINE                     1023
#define LM_IDOK                         1024
#define IDC_STATIC_BLUE2                1024
#define LM_IDCANCEL                     1025
#define IDC_SLIDER5                     1025
#define LM_IDC_LIST1                    1026
#define LM_IDC_CHECK1                   1027
#define LM_IDC_CHECK2                   1028
#define LM_IDC_CHECK3                   1029
#define LM_IDC_CHECK4                   1030
#define LM_IDC_CHECK5                   1031
#define LM_IDC_CHECK6                   1032
#define LM_IDC_CHECK7                   1033
#define LM_IDC_COMBO1                   1034
#define LM_IDC_EDIT1                    1035
#define LM_IDC_EDIT2                    1036
#define LM_IDC_EDIT3                    1037
#define LM_IDC_EDIT4                    1038
#define LM_IDC_EDIT6                    1039
#define LM_IDC_EDIT7                    1040
#define LM_IDC_EDIT8                    1041
#define LM_IDC_EDIT20                   1042
#define LM_IDC_EDIT21                   1043
#define LM_IDC_EDIT22                   1044
#define LM_IDC_BUTTON_SAVE              1045
#define LM_IDC_BUTTON2                  1046
#define LM_IDC_EDIT_START               1047
#define LM_IDC_EDIT_END                 1048
#define LM_IDC_CHECK_FORCE_COLOR        1049
#define T_COMBO_LINE_ACTION             1050
#define LM_IDC_LIST_CAMERA              1051
#define LM_IDC_EDIT_CAMERA1             1052
#define LM_IDC_EDIT_CAMERA2             1053
#define LM_IDC_EDIT_CAMERA3             1054
#define LM_IDC_EDIT_CAMERA4             1055
#define T_EDIT_LINE_JUMPSPEEDX          1056
#define LM_IDC_COMBO_CAMERA             1057
#define LM_IDC_CHECK_CAMERA             1058
#define LM_IDC_BUTTON_GETCAMERA         1059
#define LM_IDC_BUTTON_ADDCAMERA         1060
#define LM_IDC_EDIT_CAMERAINDEX         1061
#define LM_IDC_BUTTON_ADDCAMERA2        1062
#define T_EDIT1_LINE_JUMPSPEEDY         1063
#define LM_IDC_LIST_RED                 1064
#define LM_IDC_LIST_BLUE                1065
#define LM_IDC_LIST_OTHER               1066
#define LM_IDC_RADIO_RED                1067
#define LM_IDC_RADIO_BLUE               1068
#define LM_IDC_RADIO_OTHER              1069
#define LM_IDC_COMBO_DIR                1070
#define T_COMBO_ETC_ACTION              1071
#define T_EDIT_DELAYTIME                1072
#define LM_IDC_BUTTON_DELETENPC         1073
#define LM_IDC_CHECK_HIDE_USER          1074
#define LM_IDC_CHECK_HIDENPC            1075
#define LM_IDC_BUTTON_RESETKEY          1076
#define T_EDIT_ETC_NAME                 1077
#define LM_IDC_COMBO_TEAMTYPE           1078
#define LM_IDC_BUTTON_CHANGE            1079
#define LM_IDC_CHECK_HIDEWORLD          1080
#define T_LIST_ETC                      1081
#define LM_IDC_EDIT_TRIGGERID           1082
#define T_EDIT_ETC_CAMERA               1083
#define T_COMBO_MESH_PLAYTYPE           1084
#define T_CHECK_LINE_ENABLE             1085
#define T_COMBO_MESH_ANIMNAME           1086
#define T_CHECK_LOOP                    1087
#define T_LIST_SEG                      1088
#define T_COMBO_MESH_ID                 1089
#define T_COMBO_MESH_ACTION             1090
#define T_EDIT_MESH_DELAYTIME           1091
#define T_EDIT_ETC_CAMERADURATION       1092
#define LM_IDC_EDIT_LANDHEIGHT          1093
#define T_EDIT_ANIMSPEED                1094
#define T_EDIT_LINE_DELAYTIME           1095
#define T_EDIT_LINEID                   1096
#define T_EDIT_LINE_CAMERAID            1097
#define T_TRIGGER_ADD                   1098
#define T_TRIGGER_ADD_ETC               1099
#define T_TRIGGER_ADD_MESH              1100
#define T_TRIGGER_ADD_LINE              1101
#define T_UPDATE_LINE                   1102
#define T_UPDATE_ETC                    1103
#define T_UPDATE_MESH                   1104
#define T_TRIGGER_ADD_DATA              1105
#define T_UPDATE_TRIGGER                1106
#define T_TRIGGER_ADD_MESH2             1107
#define IDC_WONPOK                      1107
#define LM_IDC_COMBO2                   1108
#define T_BUTTON_INITWORLD              1109
#define LM_IDC_EDIT5                    1110
#define IDC_LAYER_CHECK1                1112
#define LM_IDC_CHECK_ONLINE             1113
#define IDC_FRU_EDIT1                   1114
#define IDC_FRU_EDIT2                   1115
#define IDC_FRU_EDIT3                   1116
#define FRU_IDOK                        1117
#define IDC_FRU_EDIT4                   1118
#define IDC_FRU_EDIT5                   1121
#define IDC_FRU_EDIT6                   1122
#define IDC_FRU_EDIT7                   1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
